# Data Collection

In [1]:
import pandas as pd
import numpy as np
from datetime import date

In [2]:
df = pd.read_csv('Data/Dialysis_Facility_Compare_-_Listing_by_Facility.csv')

# Rename columns

In [3]:
for c in df.columns:
    print(c)

Provider Number
Network
Facility Name
Five Star Date
Five Star
Five Star Data Availability Code
Address Line 1
Address Line 2
City
State
Zip
County
Phone Number
Profit or Non-Profit
Chain Owned
Chain Organization
Late Shift
# of Dialysis Stations
Offers in-center hemodialysis
Offers peritoneal dialysis
Offers home hemodialysis training
Certification or Recertification Date
Claims Date
CROWNWeb Date
STrR Date
Percentage of Medicare patients with Hgb<10 g/dL
HGB<10 data availability code
Percentage of Medicare patients with Hgb>12 g/dL
Hgb > 12 data availability code
Number of Dialysis Patients with Hgb data
Patient Transfusion data availability Code
Patient Transfusion category text
Number of patients included in the transfusion summary
Percent of Adult HD patients with Kt/V >= 1.2
Adult HD Kt/V data availability code
Percentage of Adult PD PTS with Kt/V >= 1.7
Adult PD Kt/V Data Availability Code
Percentage of Pediatric HD patients with Kt/V >= 1.2
Pediatric HD Kt/V Data Availability C

In [4]:
df.columns = [col.title() for col in df.columns]

In [5]:
df = df.rename(columns= {'Five Star Date' : 'Star Rating Date',
                        'Five Star' : 'Star Rating',
                        'Five Star Data Availability Code' : 'Star Rating Data Availability Code',
                        '# Of Dialysis Stations' : 'Number Of Dialysis Stations', 
                        'Crownweb Date' : 'CROWNWeb Date',
                        'Strr Date' : 'STrR Date', 
                        'Percentage Of Medicare Patients With Hgb<10 G/Dl' : 'Percentage Of Medicare Patients With Hgb < 10 g/dL', 
                        'Hgb<10 Data Availability Code' : 'Hgb < 10 Data Availability Code', 
                        'Percentage Of Medicare Patients With Hgb>12 G/Dl' : 'Percentage Of Medicare Patients With Hgb > 12 g/dL', 
                        'Percent Of Adult Hd Patients With Kt/V >= 1.2' : 'Percent Of Adult HD Patients With Kt/V >= 1.2', 
                        'Adult Hd Kt/V Data Availability Code' : 'Adult HD Kt/V Data Availability Code', 
                        'Percentage Of Adult Pd Pts With Kt/V >= 1.7' : 'Percentage Of Adult PD PTS With Kt/V >= 1.7',
                        'Adult Pd Kt/V Data Availability Code' : 'Adult PD Kt/V Data Availability Code', 
                        'Percentage Of Pediatric Hd Patients With Kt/V >= 1.2' : 'Percentage Of Pediatric HD Patients With Kt/V >= 1.2', 
                        'Pediatric Hd Kt/V Data Availability Code' : 'Pediatric HD Kt/V Data Availability Code', 
                        'Number Of Adult Hd Patients With Kt/V Data' : 'Number Of Adult HD Patients With Kt/V Data', 
                        'Number Of Adult Hd Patient-Months With Kt/V Data' : 'Number Of Adult HD Patient-Months With Kt/V Data', 
                        'Number Of Adult Pd Patients With Kt/V Data' : 'Number Of Adult PD Patients With Kt/V Data', 
                        'Number Of Adult Pd Patient-Months With Kt/V Data' : 'Number Of Adult PD Patient-Months With Kt/V Data', 
                        'Number Of Pediatric Hd Patients With Kt/V Data' : 'Number Of Pediatric HD Patients With Kt/V Data', 
                        'Number Of Pediatric Hd Patient-Months With Kt/V Data' : 'Number Of Pediatric HD Patient-Months With Kt/V Data', 
                        'Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 Mg/Dl)' : 'Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 mg/dL)', 
                        'Number Of Patient-Months In Serum Phosphorus Summary ' : 'Number Of Patient-Months In Serum Phosphorus Summary', 
                        'Serum Phosphorus Data Availability Code ' : 'Serum Phosphorus Data Availability Code',
                        'Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 Mg/Dl' : 'Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 mg/dL',
                        'Percentage Of Adult Patients With Serum Phosphorus Between 3.5-4.5 Mg/Dl' : 'Percentage Of Adult Patients With Serum Phosphorus Between 3.5 - 4.5 mg/dL', 
                        'Percentage Of Adult Patients With Serum Phosphorus Between 4.6-5.5 Mg/Dl' : 'Percentage Of Adult Patients With Serum Phosphorus Between 4.6 - 5.5 mg/dL', 
                        'Percentage Of Adult Patients With Serum Phosphorus Between 5.6-7.0 Mg/Dl' : 'Percentage Of Adult Patients With Serum Phosphorus Between 5.6 - 7.0 mg/dL', 
                        'Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 Mg/Dl' : 'Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 mg/dL',                         
                        'Shr Date' : 'SHR Date', 
                        'Srr Date' : 'SRR Date', 
                        'Smr Date' : 'SMR Date', 
                        'Patient Hospital Readmission Category' : 'Patient Hospital Readmission Category Text', 
                        'Number Of Pediatric Pd Patients With Kt/V Data' : 'Number Of Pediatric PD Patients With Kt/V Data', 
                        'Pediatric Pd Kt/V Data Availability Code' : 'Pediatric PD Kt/V Data Availability Code', 
                        'Number Of Pediatric Pd Patient-Months With Kt/V Data' : 'Number Of Pediatric PD Patient-Months With Kt/V Data', 
                        'Percentage Of Pediatric Pd Patients With Kt/V>=1.8' : 'Percentage Of Pediatric PD Patients With Kt/V >= 1.8', 
                        'Sir Date' : 'SIR Date', 
                        'Sir: Upper Confidence Limit (97.5%)' : 'SIR: Upper Confidence Limit (97.5%)', 
                        'Sir: Lower Confidence Limit (2.5%)' : 'SIR: Lower Confidence Limit (2.5%)', 
                        'Number Of Patient Months In Long Term Catheter Summary' : 'Number Of Patient-Months In Long Term Catheter Summary', 
                        'Number Of Patients In Npcr Summary' : 'Number Of Patients In nPCR Summary', 
                        'Number Of Patient-Months In Npcr Summary' : 'Number Of Patient-Months In nPCR Summary', 
                        'Npcr Data Availability Code' : 'nPCR Data Availability Code', 
                        'Percentage Of Pediatric Hd Patients With Npcr' : 'Percentage Of Pediatric HD Patients With nPCR', 
                        'Date_Swr' : 'SWR Date', 
                        'Swr Category Text' : 'SWR Category Text', 
                        '95% C.I. (Upper Limit) For Swr' : '95% C.I. (Upper Limit) For SWR', 
                        '95% C.I. (Lower Limit) For Swr' : '95% C.I. (Lower Limit) For SWR', 
                        'Number Of Patients In This Facility For Swr' : 'Number Of Patients In This Facility For SWR',  
                        'Pppw Category Text' : 'PPPW Category Text', 
                        '95% C.I. (Upper Limit) For Pppw' : '95% C.I. (Upper Limit) For PPPW', 
                        '95% C.I. (Lower Limit) For Pppw' : '95% C.I. (Lower Limit) For PPPW', 
                        'Number Of Patients For Pppw' : 'Number Of Patients For PPPW'
                       })

# Correct dtypes

In [6]:
isnumeric = ['Star Rating', 
             'Percentage Of Medicare Patients With Hgb < 10 g/dL', 
             'Percentage Of Medicare Patients With Hgb > 12 g/dL', 
             'Number Of Dialysis Patients With Hgb Data', 
             'Number Of Patients Included In The Transfusion Summary', 
             'Percent Of Adult HD Patients With Kt/V >= 1.2', 
             'Percentage Of Adult PD PTS With Kt/V >= 1.7', 
             'Percentage Of Pediatric HD Patients With Kt/V >= 1.2', 
             'Number Of Adult HD Patients With Kt/V Data', 
             'Number Of Adult HD Patient-Months With Kt/V Data', 
             'Number Of Adult PD Patients With Kt/V Data', 
             'Number Of Adult PD Patient-Months With Kt/V Data', 
             'Number Of Pediatric HD Patients With Kt/V Data', 
             'Number Of Pediatric HD Patient-Months With Kt/V Data', 
             'Number Of Patients In Hypercalcemia Summary', 
             'Number Of Patient-Months In Hypercalcemia Summary', 
             'Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 mg/dL)', 
             'Number Of Patients In Serum Phosphorus Summary', 
             'Number Of Patient-Months In Serum Phosphorus Summary', 
             'Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 mg/dL', 
             'Percentage Of Adult Patients With Serum Phosphorus Between 3.5 - 4.5 mg/dL', 
             'Percentage Of Adult Patients With Serum Phosphorus Between 4.6 - 5.5 mg/dL', 
             'Percentage Of Adult Patients With Serum Phosphorus Between 5.6 - 7.0 mg/dL', 
             'Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 mg/dL', 
             'Number Of Patients Included In Hospitalization Summary', 
             'Number Of Hospitalizations Included In Hospital Readmission Summary', 
             'Number Of Patients Included In Survival Summary', 
             'Mortality Rate (Facility)', 
             'Mortality Rate: Upper Confidence Limit (97.5%)', 
             'Mortality Rate: Lower Confidence Limit (2.5%)', 
             'Readmission Rate (Facility)', 
             'Readmission Rate: Upper Confidence Limit (97.5%)', 
             'Readmission Rate: Lower Confidence Limit (2.5%)', 
             'Hospitalization Rate (Facility)', 
             'Hospitalization Rate: Upper Confidence Limit (97.5%)', 
             'Hospitalization Rate: Lower Confidence Limit (2.5%)', 
             'Number Of Pediatric PD Patients With Kt/V Data', 
             'Number Of Pediatric PD Patient-Months With Kt/V Data', 
             'Percentage Of Pediatric PD Patients With Kt/V >= 1.8', 
             'Standard Infection Ratio', 
             'SIR: Upper Confidence Limit (97.5%)', 
             'SIR: Lower Confidence Limit (2.5%)', 
             'Transfusion Rate (Facility)', 
             'Transfusion Rate: Upper Confidence Limit (97.5%)', 
             'Transfusion Rate: Lower Confidence Limit (2.5%)', 
             'Number Of Patients Included In Fistula Summary', 
             'Fistula Rate (Facility)', 
             'Fistula Rate: Upper Confidence Limit (97.5%)', 
             'Fistula Rate: Lower Confidence Limit (2.5%)', 
             'Number Of Patients In Long Term Catheter Summary', 
             'Number Of Patient-Months In Long Term Catheter Summary', 
             'Percentage Of Adult Patients With Long Term Catheter In Use', 
             'Number Of Patients In nPCR Summary', 
             'Number Of Patient-Months In nPCR Summary', 
             'Percentage Of Pediatric HD Patients With nPCR', 
             '95% C.I. (Upper Limit) For SWR', 
             '95% C.I. (Lower Limit) For SWR', 
             'Number Of Patients In This Facility For SWR', 
             'Standardized First Kidney Transplant Waitlist Ratio', 
             '95% C.I. (Upper Limit) For PPPW', 
             '95% C.I. (Lower Limit) For PPPW', 
             'Number Of Patients For PPPW', 
             'Percentage Of Prevalent Patients Waitlisted']

In [7]:
for col in  df[isnumeric]:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [8]:
isdateframe = ['Star Rating Date', 'Claims Date', 'CROWNWeb Date', 'STrR Date', 'SHR Date', 'SRR Date', 'SMR Date', 'SIR Date', 'SWR Date']

In [9]:
isdate = ['Certification Or Recertification Date']

# Missing Values

In [10]:
df.replace(to_replace=['Not Available'], value=np.nan, inplace=True)

In [11]:
availabilitycode = ['Star Rating Data Availability Code', 
                    'Hgb < 10 Data Availability Code', 
                    'Hgb > 12 Data Availability Code', 
                    'Patient Transfusion Data Availability Code', 
                    'Adult HD Kt/V Data Availability Code', 
                    'Adult PD Kt/V Data Availability Code', 
                    'Pediatric HD Kt/V Data Availability Code', 
                    'Hypercalcemia Data Availability Code', 
                    'Serum Phosphorus Data Availability Code', 
                    'Patient Hospitalization Data Availability Code', 
                    'Patient Hospital Readmission Data Availability Code', 
                    'Patient Survival Data Availability Code', 
                    'Pediatric PD Kt/V Data Availability Code', 
                    'Patient Infection Data Availability Code', 
                    'Fistula Data Availability Code', 
                    'Long Term Catheter Data Availability Code', 
                    'nPCR Data Availability Code', 
                    'Patient Transplant Waitlist Data Availability Code', 
                    'Patient Prevalent Transplant Waitlist Data Availability Code']

In [12]:
df[availabilitycode] = df[availabilitycode].replace(to_replace=[1], value=np.nan)

# Data Definition

### Head & Tail

In [13]:
df.iloc[:, :60].head().T

0  \
Provider Number                                                       32647   
Network                                                                  15   
Facility Name                                            FMC NORTH MOUNTAIN   
Star Rating Date                                    01/01/2016 - 12/31/2019   
Star Rating                                                               4   
Star Rating Data Availability Code                                      NaN   
Address Line 1                                      16605 NORTH 28TH AVENUE   
Address Line 2                                                    SUITE 100   
City                                                                PHOENIX   
State                                                                    AZ   
Zip                                                                   85053   
County                                                             MARICOPA   
Phone Number                                                 (602) 863-7954   
Profit Or Non-Profit                                                 Profit   
Chain Owned                                                             Yes   
Chain Organization                                   FRESENIUS MEDICAL CARE   
Late Shift                                                                0   
Number Of Dialysis Stations                                              25   
Offers In-Center Hemodialysis                                             1   
Offers Peritoneal Dialysis                                                0   
Offers Home Hemodialysis Training                                         0   
Certification Or Recertification Date                            10/12/2016   
Claims Date                                         01/01/2019 - 12/31/2019   
CROWNWeb Date                                       01/01/2019 - 12/31/2019   
STrR Date                                           01/01/2019 - 12/31/2019   
Percentage Of Medicare Patients With Hgb < 10 g/dL                        8   
Hgb < 10 Data Availability Code                                         NaN   
Percentage Of Medicare Patients With Hgb > 12 g/dL                        0   
Hgb > 12 Data Availability Code                                         NaN   
Number Of Dialysis Patients With Hgb Data                                25   
Patient Transfusion Data Availability Code                              NaN   
Patient Transfusion Category Text                               As Expected   
Number Of Patients Included In The Transfusion ...                       56   
Percent Of Adult HD Patients With Kt/V >= 1.2                            98   
Adult HD Kt/V Data Availability Code                                    NaN   
Percentage Of Adult PD PTS With Kt/V >= 1.7                             NaN   
Adult PD Kt/V Data Availability Code                                    257   
Percentage Of Pediatric HD Patients With Kt/V >...                      NaN   
Pediatric HD Kt/V Data Availability Code                                259   
Number Of Adult HD Patients With Kt/V Data                               91   
Number Of Adult HD Patient-Months With Kt/V Data                        608   
Number Of Adult PD Patients With Kt/V Data                                0   
Number Of Adult PD Patient-Months With Kt/V Data                        NaN   
Number Of Pediatric HD Patients With Kt/V Data                            0   
Number Of Pediatric HD Patient-Months With Kt/V...                      NaN   
Hypercalcemia Data Availability Code                                    NaN   
Number Of Patients In Hypercalcemia Summary                              96   
Number Of Patient-Months In Hypercalcemia Summary                       665   
Percentage Of Adult Patients With Hypercalcemia...                        2   
Number Of Patients In Serum Phosphorus Summary                          108   
Number Of Patient-Months In Serum Phosphorus 

In [14]:
df.iloc[:, 60:].tail().T

7719  \
Patient Hospitalization Category Text                               As Expected   
Patient Hospitalization Data Availability Code                              NaN   
Patient Hospital Readmission Category Text                          As Expected   
Patient Hospital Readmission Data Availability ...                          NaN   
Patient Survival Category Text                                      As Expected   
Patient Survival Data Availability Code                                     NaN   
Number Of Patients Included In Hospitalization ...                           22   
Number Of Hospitalizations Included In Hospital...                           38   
Number Of Patients Included In Survival Summary                              77   
Mortality Rate (Facility)                                                  29.7   
Mortality Rate: Upper Confidence Limit (97.5%)                             49.1   
Mortality Rate: Lower Confidence Limit (2.5%)                              16.6   
Readmission Rate (Facility)                                                43.5   
Readmission Rate: Upper Confidence Limit (97.5%)                             61   
Readmission Rate: Lower Confidence Limit (2.5%)                              27   
Hospitalization Rate (Facility)                                           251.3   
Hospitalization Rate: Upper Confidence Limit (9...                        456.2   
Hospitalization Rate: Lower Confidence Limit (2...                        144.6   
Number Of Pediatric PD Patients With Kt/V Data                                0   
Pediatric PD Kt/V Data Availability Code                                    259   
Number Of Pediatric PD Patient-Months With Kt/V...                          NaN   
Percentage Of Pediatric PD Patients With Kt/V >...                          NaN   
SIR Date                                                01/01/2019 - 12/31/2019   
Patient Infection Data Availability Code                                    NaN   
Patient Infection Category Text                                     As Expected   
Standard Infection Ratio                                                      0   
SIR: Upper Confidence Limit (97.5%)                                        1.82   
SIR: Lower Confidence Limit (2.5%)                                          NaN   
Transfusion Rate (Facility)                                                 NaN   
Transfusion Rate: Upper Confidence Limit (97.5%)                            NaN   
Transfusion Rate: Lower Confidence Limit (2.5%)                             NaN   
Fistula Data Availability Code                                              NaN   
Fistula Category Text                                               As Expected   
Number Of Patients Included In Fistula Summary                               24   
Fistula Rate (Facility)                                                    51.1   
Fistula Rate: Upper Confidence Limit (97.5%)                               87.2   
Fistula Rate: Lower Confidence Limit (2.5%)                                12.5   
Number Of Patients In Long Term Catheter Summary                             24   
Number Of Patient-Months In Long Term Catheter ...                          197   
Long Term Catheter Data Availability Code                                   NaN   
Percentage Of Adult Patients With Long Term Cat...                           21   
Number Of Patients In nPCR Summary                                            0   
Number Of Patient-Months In nPCR Summary                                    NaN   
nPCR Data Availability Code                                                 259   
Percentage Of Pediatric HD Patients With nPCR                               NaN   
SWR Date                                                01/01/2016 - 12/31/2018   
SWR Category Text                                                           NaN   
Patient Transplant Waitlist Data Availability Code                          199   
95% C.I.

### Shape

In [15]:
df.shape

(7724, 119)

### Data Types

In [16]:
df.iloc[:, :60].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7724 entries, 0 to 7723
Data columns (total 60 columns):
 #   Column                                                                                   Non-Null Count  Dtype  
---  ------                                                                                   --------------  -----  
 0   Provider Number                                                                          7724 non-null   int64  
 1   Network                                                                                  7724 non-null   int64  
 2   Facility Name                                                                            7724 non-null   object 
 3   Star Rating Date                                                                         7724 non-null   object 
 4   Star Rating                                                                              7041 non-null   float64
 5   Star Rating Data Availability Code                            

In [17]:
df.iloc[:, 60:].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7724 entries, 0 to 7723
Data columns (total 59 columns):
 #   Column                                                               Non-Null Count  Dtype  
---  ------                                                               --------------  -----  
 0   Patient Hospitalization Category Text                                7185 non-null   object 
 1   Patient Hospitalization Data Availability Code                       539 non-null    float64
 2   Patient Hospital Readmission Category Text                           7118 non-null   object 
 3   Patient Hospital Readmission Data Availability Code                  606 non-null    float64
 4   Patient Survival Category Text                                       7012 non-null   object 
 5   Patient Survival Data Availability Code                              712 non-null    float64
 6   Number Of Patients Included In Hospitalization Summary               7614 non-null   float64
 7   Number

### Count of unique values or codes

In [18]:
df.iloc[:, :60].nunique()

Provider Number                                                                            7724
Network                                                                                      18
Facility Name                                                                              7503
Star Rating Date                                                                              1
Star Rating                                                                                   5
Star Rating Data Availability Code                                                            3
Address Line 1                                                                             7670
Address Line 2                                                                              600
City                                                                                       3009
State                                                                                        56
Zip                                     

In [19]:
df.iloc[:, 60:].nunique()

Patient Hospitalization Category Text                                     3
Patient Hospitalization Data Availability Code                            4
Patient Hospital Readmission Category Text                                3
Patient Hospital Readmission Data Availability Code                       3
Patient Survival Category Text                                            3
Patient Survival Data Availability Code                                   4
Number Of Patients Included In Hospitalization Summary                  250
Number Of Hospitalizations Included In Hospital Readmission Summary     281
Number Of Patients Included In Survival Summary                         795
Mortality Rate (Facility)                                               411
Mortality Rate: Upper Confidence Limit (97.5%)                          570
Mortality Rate: Lower Confidence Limit (2.5%)                           336
Readmission Rate (Facility)                                             477
Readmission 

### Percent unique values

In [20]:
df.iloc[:, :60].nunique()/df.iloc[:, :60].size

Provider Number                                                                            0.016667
Network                                                                                    0.000039
Facility Name                                                                              0.016190
Star Rating Date                                                                           0.000002
Star Rating                                                                                0.000011
Star Rating Data Availability Code                                                         0.000006
Address Line 1                                                                             0.016550
Address Line 2                                                                             0.001295
City                                                                                       0.006493
State                                                                                      0.000121


In [21]:
df.iloc[:, 60:].nunique()/df.iloc[:, 60:].size

Patient Hospitalization Category Text                                  0.000007
Patient Hospitalization Data Availability Code                         0.000009
Patient Hospital Readmission Category Text                             0.000007
Patient Hospital Readmission Data Availability Code                    0.000007
Patient Survival Category Text                                         0.000007
Patient Survival Data Availability Code                                0.000009
Number Of Patients Included In Hospitalization Summary                 0.000549
Number Of Hospitalizations Included In Hospital Readmission Summary    0.000617
Number Of Patients Included In Survival Summary                        0.001745
Mortality Rate (Facility)                                              0.000902
Mortality Rate: Upper Confidence Limit (97.5%)                         0.001251
Mortality Rate: Lower Confidence Limit (2.5%)                          0.000737
Readmission Rate (Facility)             

### Summary statistics

In [22]:
df.iloc[:, :30].describe()

Provider Number      Network  Star Rating  \
count      7724.000000  7724.000000  7041.000000   
mean     317574.641895     9.658985     3.755006   
std      194129.142332     4.731066     1.018465   
min       12306.000000     1.000000     1.000000   
25%      142841.750000     6.000000     3.000000   
50%      332317.000000     9.000000     4.000000   
75%      452550.500000    14.000000     5.000000   
max      852574.000000    18.000000     5.000000   

       Star Rating Data Availability Code           Zip   Late Shift  \
count                          683.000000   7724.000000  7724.000000   
mean                           259.604685  50287.112118     0.165847   
std                              0.802548  27692.262592     0.371967   
min                            258.000000    603.000000     0.000000   
25%                            260.000000  29497.750000     0.000000   
50%                            260.000000  45952.000000     0.000000   
75%                            260.000000  76104.250000     0.000000   
max                            261.000000  99801.000000     1.000000   

       Number Of Dialysis Stations  Offers In-Center Hemodialysis  \
count                  7724.000000                    7724.000000   
mean                     17.485111                       0.940057   
std                       8.473365                       0.237397   
min                       0.000000                       0.000000   
25%                      12.000000                       1.000000   
50%                      17.000000                       1.000000   
75%                      22.000000                       1.000000   
max                      80.000000                       1.000000   

       Offers Peritoneal Dialysis  Offers Home Hemodialysis Training  \
count                 7724.000000                        7724.000000   
mean                     0.523175                           0.289746   
std                      0.499495                           0.453674   
min                      0.000000                           0.000000   
25%                      0.000000                           0.000000   
50%                      1.000000                           0.000000   
75%                      1.000000                           1.000000   
max                      1.000000                           1.000000   

       Percentage Of Medicare Patients With Hgb < 10 g/dL  \
count                                        6639.000000    
mean                                           20.044585    
std                                            12.056803    
min                                             0.000000    
25%                                            12.000000    
50%                                            18.000000    
75%                                            26.000000    
max                                           100.000000    

       Hgb < 10 Data Availability Code  \
count                      1085.000000   
mean                        219.694009   
std                          27.971295   
min                         199.000000   
25%                         199.000000   
50%                         199.000000   
75%                         258.000000   
max                         258.000000   

       Percentage Of Medicare Patients With Hgb > 12 g/dL  \
count                                        6639.000000    
mean                                            0.234222    
std                                             1.371864    
min                                             0.000000    
25%                                             0.000000    
50%                                             0.000000    
75%                                             0.000000    
max                                            40.000000    

       Hgb > 12 Data Availability Code  \
count                      1085.000000   
mean                        219.694009   
std          

In [23]:
df.iloc[:, 30:50].describe()

Patient Transfusion Data Availability Code  \
count                                 1160.000000   
mean                                   219.753448   
std                                     28.127214   
min                                    199.000000   
25%                                    199.000000   
50%                                    199.000000   
75%                                    258.000000   
max                                    258.000000   

       Number Of Patients Included In The Transfusion Summary  \
count                                        7615.000000        
mean                                           55.389494        
std                                            36.622383        
min                                             0.000000        
25%                                            30.000000        
50%                                            50.000000        
75%                                            74.000000        
max                                           439.000000        

       Percent Of Adult HD Patients With Kt/V >= 1.2  \
count                                    6854.000000   
mean                                       96.979282   
std                                         4.638218   
min                                         0.000000   
25%                                        96.000000   
50%                                        98.000000   
75%                                        99.000000   
max                                       100.000000   

       Adult HD Kt/V Data Availability Code  \
count                            870.000000   
mean                             227.621839   
std                               28.878153   
min                              199.000000   
25%                              199.000000   
50%                              201.000000   
75%                              258.000000   
max                              258.000000   

       Percentage Of Adult PD PTS With Kt/V >= 1.7  \
count                                  2214.000000   
mean                                     91.284553   
std                                      10.187992   
min                                       0.000000   
25%                                      89.000000   
50%                                      94.000000   
75%                                      97.000000   
max                                     100.000000   

       Adult PD Kt/V Data Availability Code  \
count                           5510.000000   
mean                             237.102178   
std                               27.280281   
min                              199.000000   
25%                              201.000000   
50%                              257.000000   
75%                              257.000000   
max                              258.000000   

       Percentage Of Pediatric HD Patients With Kt/V >= 1.2  \
count                                          14.000000      
mean                                           92.500000      
std                                             6.406127      
min                                            76.000000      
25%                                            89.250000      
50%                                            93.500000      
75%                                            97.000000      
max                                           100.000000      

       Pediatric HD Kt/V Data Availability Code  \
count                               7710.000000   
mean                                 255.786122   
std                                   13.344135   
min                                  199.000000   
25%                                  259.000000   
50%                                  259.000000   
75%                                  259.000000   
max                                  259.000000   

       Number Of Adult HD Patients With Kt/V Data  \
count                 

In [24]:
df.iloc[:, 50:70].describe()

Number Of Patient-Months In Serum Phosphorus Summary  \
count                                        7553.000000      
mean                                          757.042897      
std                                           518.925441      
min                                             0.000000      
25%                                           384.000000      
50%                                           663.000000      
75%                                          1017.000000      
max                                          5421.000000      

       Serum Phosphorus Data Availability Code  \
count                               414.000000   
mean                                236.886473   
std                                  28.194914   
min                                 199.000000   
25%                                 199.000000   
50%                                 258.000000   
75%                                 258.000000   
max                                 258.000000   

       Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 mg/dL  \
count                                        7310.000000                        
mean                                            7.763885                        
std                                             3.298454                        
min                                             0.000000                        
25%                                             6.000000                        
50%                                             7.000000                        
75%                                             9.000000                        
max                                            42.000000                        

       Percentage Of Adult Patients With Serum Phosphorus Between 3.5 - 4.5 mg/dL  \
count                                        7310.000000                            
mean                                           24.105198                            
std                                             4.780989                            
min                                             0.000000                            
25%                                            21.000000                            
50%                                            24.000000                            
75%                                            27.000000                            
max                                            56.000000                            

       Percentage Of Adult Patients With Serum Phosphorus Between 4.6 - 5.5 mg/dL  \
count                                        7310.000000                            
mean                                           31.047332                            
std                                             5.199530                            
min                                             7.000000                            
25%                                            27.000000                            
50%                                            31.000000                            
75%                                            34.000000                            
max                                            67.000000                            

       Percentage Of Adult Patients With Serum Phosphorus Between 5.6 - 7.0 mg/dL  \
count                                        7310.000000                            
mean                                           22.305335                            
std                                             5.128003                            
min                                             2.000000                            
25%                                            19.000000                            
50%                                            22.000000                            
75%                                            26.000000                            
max                                           

In [25]:
df.iloc[:, 70:90].describe()

Mortality Rate: Upper Confidence Limit (97.5%)  \
count                                     7012.000000   
mean                                        33.101226   
std                                         10.504489   
min                                         10.600000   
25%                                         26.500000   
50%                                         30.900000   
75%                                         37.200000   
max                                        121.500000   

       Mortality Rate: Lower Confidence Limit (2.5%)  \
count                                    7012.000000   
mean                                       14.972704   
std                                         5.309535   
min                                         0.000000   
25%                                        11.800000   
50%                                        15.000000   
75%                                        18.200000   
max                                        55.000000   

       Readmission Rate (Facility)  \
count                  7118.000000   
mean                     26.934125   
std                       8.000547   
min                       0.000000   
25%                      22.000000   
50%                      27.000000   
75%                      31.800000   
max                      72.500000   

       Readmission Rate: Upper Confidence Limit (97.5%)  \
count                                       7118.000000   
mean                                          43.381174   
std                                            9.855395   
min                                           13.600000   
25%                                           36.900000   
50%                                           42.300000   
75%                                           48.400000   
max                                          104.000000   

       Readmission Rate: Lower Confidence Limit (2.5%)  \
count                                      7118.000000   
mean                                         14.786204   
std                                           6.842420   
min                                           0.000000   
25%                                          10.100000   
50%                                          15.000000   
75%                                          19.400000   
max                                          47.800000   

       Hospitalization Rate (Facility)  \
count                      7185.000000   
mean                        188.738386   
std                          51.273668   
min                          22.900000   
25%                         154.700000   
50%                         185.000000   
75%                         218.600000   
max                         529.900000   

       Hospitalization Rate: Upper Confidence Limit (97.5%)  \
count                                        7185.000000      
mean                                          323.795992      
std                                            82.038913      
min                                           133.000000      
25%                                           270.000000      
50%                                           310.900000      
75%                                           359.900000      
max                                           903.600000      

       Hospitalization Rate: Lower Confidence Limit (2.5%)  \
count                                        7185.000000     
mean                                          117.544690     
std                                            40.162835     
min                                             2.300000     
25%                                            90.500000     
50%                                           115.500000     
75%                                           142.300000     
max                                           362.300000     

       Number Of Pediatric PD Patients With Kt/V Data  \
count                      

In [26]:
df.iloc[:, 90:].describe()

Transfusion Rate: Lower Confidence Limit (2.5%)  \
count                                      6564.000000   
mean                                          7.246283   
std                                           8.816395   
min                                           0.000000   
25%                                           1.200000   
50%                                           4.500000   
75%                                          10.200000   
max                                         132.400000   

       Fistula Data Availability Code  \
count                      707.000000   
mean                       231.295615   
std                         28.908991   
min                        199.000000   
25%                        199.000000   
50%                        256.000000   
75%                        258.000000   
max                        258.000000   

       Number Of Patients Included In Fistula Summary  \
count                                     7614.000000   
mean                                        78.327160   
std                                         53.025111   
min                                          0.000000   
25%                                         41.000000   
50%                                         72.000000   
75%                                        107.000000   
max                                        906.000000   

       Fistula Rate (Facility)  Fistula Rate: Upper Confidence Limit (97.5%)  \
count              7017.000000                                   7017.000000   
mean                 62.767579                                     83.681801   
std                  10.793898                                     10.831076   
min                   0.000000                                      0.000000   
25%                  56.100000                                     77.100000   
50%                  63.300000                                     84.200000   
75%                  70.100000                                     91.200000   
max                 100.000000                                    100.000000   

       Fistula Rate: Lower Confidence Limit (2.5%)  \
count                                  7017.000000   
mean                                     40.027334   
std                                      14.538320   
min                                       0.000000   
25%                                      31.300000   
50%                                      41.100000   
75%                                      50.200000   
max                                     100.000000   

       Number Of Patients In Long Term Catheter Summary  \
count                                       7616.000000   
mean                                          78.330488   
std                                           53.025502   
min                                            0.000000   
25%                                           41.000000   
50%                                           72.000000   
75%                                          107.000000   
max                                          906.000000   

       Number Of Patient-Months In Long Term Catheter Summary  \
count                                        7396.000000        
mean                                          697.857896        
std                                           476.410847        
min                                             1.000000        
25%                                           354.000000        
50%                                           628.500000        
75%                                           950.250000        
max                                          4155.000000        

       Long Term Catheter Data Availability Code  \
count                                 707.000000   
mean                                  231.267327   
std                                    28.883778   
min                                   199.000000   
25%           

### Range of values per column

In [27]:
df.iloc[:, :60].agg([min, max]).T

min  \
Provider Number                                                          12306   
Network                                                                      1   
Facility Name                                       A UNIQUE KIDNEY CENTER LLC   
Star Rating Date                                       01/01/2016 - 12/31/2019   
Star Rating                                                                  1   
Star Rating Data Availability Code                                         258   
Address Line 1                                          # 7 PROFESSIONAL DRIVE   
City                                                                 ABBEVILLE   
State                                                                       AK   
Zip                                                                        603   
County                                                               ABBEVILLE   
Phone Number                                                    (201) 262-0429   
Chain Owned                                                                 No   
Late Shift                                                                   0   
Number Of Dialysis Stations                                                  0   
Offers In-Center Hemodialysis                                                0   
Offers Peritoneal Dialysis                                                   0   
Offers Home Hemodialysis Training                                            0   
Certification Or Recertification Date                               01/01/1968   
Claims Date                                            01/01/2019 - 12/31/2019   
CROWNWeb Date                                          01/01/2019 - 12/31/2019   
STrR Date                                              01/01/2019 - 12/31/2019   
Percentage Of Medicare Patients With Hgb < 10 g/dL                           0   
Hgb < 10 Data Availability Code                                            199   
Percentage Of Medicare Patients With Hgb > 12 g/dL                           0   
Hgb > 12 Data Availability Code                                            199   
Number Of Dialysis Patients With Hgb Data                                    0   
Patient Transfusion Data Availability Code                                 199   
Number Of Patients Included In The Transfusion ...                           0   
Percent Of Adult HD Patients With Kt/V >= 1.2                                0   
Adult HD Kt/V Data Availability Code                                       199   
Percentage Of Adult PD PTS With Kt/V >= 1.7                                  0   
Adult PD Kt/V Data Availability Code                                       199   
Percentage Of Pediatric HD Patients With Kt/V >...                          76   
Pediatric HD Kt/V Data Availability Code                                   199   
Number Of Adult HD Patients With Kt/V Data                                   0   
Number Of Adult HD Patient-Months With Kt/V Data                             1   
Number Of Adult PD Patients With Kt/V Data                                   0   
Number Of Adult PD Patient-Months With Kt/V Data                             1   
Number Of Pediatric HD Patients With Kt/V Data                               0   
Number Of Pediatric HD Patient-Months With Kt/V...                           1   
Hypercalcemia Data Availability Code                                       199   
Number Of Patients In Hypercalcemia Summary                                  0   
Number Of Patient-Months In Hypercalcemia Summary                            0   
Percentage Of Adult Patients With Hypercalcemia...                           0   
Number Of Patients In Serum Phosphorus Summary                               0   
Number Of Patient-Months In Serum Phosphorus Su...                           0   
Serum Phosphorus Data Availability Code                                    199   
Percentage Of Adult Patients With Serum Phospho...       

In [28]:
df.iloc[:, 60:].agg([min, max]).T

min  \
Patient Hospitalization Data Availability Code                          199   
Patient Hospital Readmission Data Availability ...                      199   
Patient Survival Data Availability Code                                 199   
Number Of Patients Included In Hospitalization ...                        0   
Number Of Hospitalizations Included In Hospital...                        0   
Number Of Patients Included In Survival Summary                           0   
Mortality Rate (Facility)                                                 0   
Mortality Rate: Upper Confidence Limit (97.5%)                         10.6   
Mortality Rate: Lower Confidence Limit (2.5%)                             0   
Readmission Rate (Facility)                                               0   
Readmission Rate: Upper Confidence Limit (97.5%)                       13.6   
Readmission Rate: Lower Confidence Limit (2.5%)                           0   
Hospitalization Rate (Facility)                                        22.9   
Hospitalization Rate: Upper Confidence Limit (9...                      133   
Hospitalization Rate: Lower Confidence Limit (2...                      2.3   
Number Of Pediatric PD Patients With Kt/V Data                            0   
Pediatric PD Kt/V Data Availability Code                                199   
Number Of Pediatric PD Patient-Months With Kt/V...                        1   
Percentage Of Pediatric PD Patients With Kt/V >...                        4   
SIR Date                                            01/01/2019 - 12/31/2019   
Patient Infection Data Availability Code                                199   
Standard Infection Ratio                                                  0   
SIR: Upper Confidence Limit (97.5%)                                     0.2   
SIR: Lower Confidence Limit (2.5%)                                        0   
Transfusion Rate (Facility)                                               0   
Transfusion Rate: Upper Confidence Limit (97.5%)                         14   
Transfusion Rate: Lower Confidence Limit (2.5%)                           0   
Fistula Data Availability Code                                          199   
Number Of Patients Included In Fistula Summary                            0   
Fistula Rate (Facility)                                                   0   
Fistula Rate: Upper Confidence Limit (97.5%)                              0   
Fistula Rate: Lower Confidence Limit (2.5%)                               0   
Number Of Patients In Long Term Catheter Summary                          0   
Number Of Patient-Months In Long Term Catheter ...                        1   
Long Term Catheter Data Availability Code                               199   
Percentage Of Adult Patients With Long Term Cat...                        0   
Number Of Patients In nPCR Summary                                        0   
Number Of Patient-Months In nPCR Summary                                  1   
nPCR Data Availability Code                                             199   
Percentage Of Pediatric HD Patients With nPCR                            37   
SWR Date                                            01/01/2016 - 12/31/2018   
Patient Transplant Waitlist Data Availability Code                      199   
95% C.I. (Upper Limit) For SWR                                         0.27   
95% C.I. (Lower Limit) For SWR                                            0   
Number Of Patients In This Facility For SWR                               0   
Standardized First Kidney Transplant Waitlist R...                        0   
Patient Prevalent Transplant Waitlist Data Avai...                      199   
95% C.I. (Upper Limit) For PPPW                                           0   
95% C.I. (Lower Limit) For PPPW                                           0   
Number Of Patients For PPPW                                               0   
Percentage Of Prevalent Patients Waitlisted

### Duplicate rows

In [29]:
df[df.duplicated()]

Empty DataFrame
Columns: [Provider Number, Network, Facility Name, Star Rating Date, Star Rating, Star Rating Data Availability Code, Address Line 1, Address Line 2, City, State, Zip, County, Phone Number, Profit Or Non-Profit, Chain Owned, Chain Organization, Late Shift, Number Of Dialysis Stations, Offers In-Center Hemodialysis, Offers Peritoneal Dialysis, Offers Home Hemodialysis Training, Certification Or Recertification Date, Claims Date, CROWNWeb Date, STrR Date, Percentage Of Medicare Patients With Hgb < 10 g/dL, Hgb < 10 Data Availability Code, Percentage Of Medicare Patients With Hgb > 12 g/dL, Hgb > 12 Data Availability Code, Number Of Dialysis Patients With Hgb Data, Patient Transfusion Data Availability Code, Patient Transfusion Category Text, Number Of Patients Included In The Transfusion Summary, Percent Of Adult HD Patients With Kt/V >= 1.2, Adult HD Kt/V Data Availability Code, Percentage Of Adult PD PTS With Kt/V >= 1.7, Adult PD Kt/V Data Availability Code, Percentage Of Pediatric HD Patients With Kt/V >= 1.2, Pediatric HD Kt/V Data Availability Code, Number Of Adult HD Patients With Kt/V Data, Number Of Adult HD Patient-Months With Kt/V Data, Number Of Adult PD Patients With Kt/V Data, Number Of Adult PD Patient-Months With Kt/V Data, Number Of Pediatric HD Patients With Kt/V Data, Number Of Pediatric HD Patient-Months With Kt/V Data, Hypercalcemia Data Availability Code, Number Of Patients In Hypercalcemia Summary, Number Of Patient-Months In Hypercalcemia Summary, Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 mg/dL), Number Of Patients In Serum Phosphorus Summary, Number Of Patient-Months In Serum Phosphorus Summary, Serum Phosphorus Data Availability Code, Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 mg/dL, Percentage Of Adult Patients With Serum Phosphorus Between 3.5 - 4.5 mg/dL, Percentage Of Adult Patients With Serum Phosphorus Between 4.6 - 5.5 mg/dL, Percentage Of Adult Patients With Serum Phosphorus Between 5.6 - 7.0 mg/dL, Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 mg/dL, SHR Date, SRR Date, SMR Date, Patient Hospitalization Category Text, Patient Hospitalization Data Availability Code, Patient Hospital Readmission Category Text, Patient Hospital Readmission Data Availability Code, Patient Survival Category Text, Patient Survival Data Availability Code, Number Of Patients Included In Hospitalization Summary, Number Of Hospitalizations Included In Hospital Readmission Summary, Number Of Patients Included In Survival Summary, Mortality Rate (Facility), Mortality Rate: Upper Confidence Limit (97.5%), Mortality Rate: Lower Confidence Limit (2.5%), Readmission Rate (Facility), Readmission Rate: Upper Confidence Limit (97.5%), Readmission Rate: Lower Confidence Limit (2.5%), Hospitalization Rate (Facility), Hospitalization Rate: Upper Confidence Limit (97.5%), Hospitalization Rate: Lower Confidence Limit (2.5%), Number Of Pediatric PD Patients With Kt/V Data, Pediatric PD Kt/V Data Availability Code, Number Of Pediatric PD Patient-Months With Kt/V Data, Percentage Of Pediatric PD Patients With Kt/V >= 1.8, SIR Date, Patient Infection Data Availability Code, Patient Infection Category Text, Standard Infection Ratio, SIR: Upper Confidence Limit (97.5%), SIR: Lower Confidence Limit (2.5%), Transfusion Rate (Facility), Transfusion Rate: Upper Confidence Limit (97.5%), Transfusion Rate: Lower Confidence Limit (2.5%), Fistula Data Availability Code, Fistula Category Text, Number Of Patients Included In Fistula Summary, Fistula Rate (Facility), Fistula Rate: Upper Confidence Limit (97.5%), Fistula Rate: Lower Confidence Limit (2.5%), Number Of Patients In Long Term Catheter Summary, Number Of Patient-Months In Long Term Catheter Summary, Long Term Catheter Data Availability Code, ...]
Index: []

[0 rows x 119 columns]

# Data Definitions

### Provider Number
Data type: int64

Value count: 7626

Number of unique values: 7626

Percent unique values: 0.016667

Ranges of values: 12306 - 852568

Length of values: 5, 6

Description: Lists the numeric code used to identify the provider listed.

In [30]:
set([(len(str(num))) for num in df['Provider Number']])

{5, 6}

### Network
Data type: int64

Value count: 7626 

Number of unique values: 18

Percent unique values: 0.000039

Ranges of values: 1 - 18

Length of values: 1, 2

Description: Lists the numeric code representing geographic area of all Medicare-approved ESRD (End Stage Renal Disease) facilities. 
Map of the network can be found here:
https://esrdncc.org/en/ESRD-network-map/

Value description:
- 1   : Network 1 (CT, ME, MA, NH,RI,VT)
- 2   : Network 2 (NY)
- 3   : Network 3 (NJ, PR, VI) 
- 4   : Network 4 (DE, PA)
- 5   : Network 5 (DC, MD, VA,WV)
- 6   : Network 6 (GA, NC, SC)
- 7   : Network 7 (FL)
- 8   : Network 8 (AL, MS, TN)
- 9   : Network 9 (IN, KY, OH)
- 10  : Network 10 (IL)
- 11  : Network 11 (MI, MN, ND, SD,WI)
- 12  : Network 12 (IA, KS, MO, NE)
- 13  : Network 13 (AR, LA, OK)
- 14  : Network 14 (TX)
- 15  : Network 15 (AZ, CO, NV, NM, UT,WY)
- 16  : Network 16 (AK, ID, MT, OR, WA)
- 17  : Network 17 (AS, GU, HI, MP, N. CA)
- 18  : Network 18 (S. CA)

In [31]:
df['Network'].value_counts()

6     788
14    748
9     652
11    514
7     510
8     485
5     454
18    445
15    384
4     362
13    351
10    347
12    337
2     332
17    327
3     254
16    230
1     204
Name: Network, dtype: int64

### Facility Name
Data type: object

Value count: 7626 

Number of unique values: 7448

Percent unique values: 0.016278

Range of values: A UNIQUE KIDNEY CENTER LLC - ZILLMAR DIALYSIS LLC

Length of values: 7 - 68

Description: Lists the name of the facility listed.

In [32]:
min(set([(len(str(num))) for num in df['Facility Name']]))

7

In [33]:
max(set([(len(str(num))) for num in df['Facility Name']]))

75

### Star Rating Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "01/01/2015 - 12/31/2018"

Length of values: 23

Description: Lists the data collection period for the five star rating.

In [34]:
set([(len(str(num))) for num in df['Star Rating Date']])

{23}

### Star Rating
Data type: float64

Value count: 6725

Number of unique values: 5

Percent unique values: 0.000011

Ranges of values: 1 - 5

Length of values: 1, 13

Description: Lists the 5-star rating for the facility. The “Dialysis Facility Compare (DFC) Star Program” is a rating system developed by Medicare that assigns 1 to 5 stars to dialysis facilities by comparing the health of the patients in their clinics to the patients in other dialysis facilities across the country.

In [35]:
df['Star Rating'].value_counts()

3.0    2391
5.0    2053
4.0    1988
2.0     440
1.0     169
Name: Star Rating, dtype: int64

### Star Rating Data Availability Code
Data type: float64

Value count: 901

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: 258, 260, 261

Length of values: 3

Description: Lists whether the facility had sufficient five star data available or the reason for why the data is not available.

Value description:
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 
- 260 : Not enough quality measure data to calculate a star rating.
- 261 : Medicare determined that at least one measure included in the star rating calculation was not accurate for this dialysis center.

In [36]:
df['Star Rating Data Availability Code'].dtype

dtype('float64')

In [37]:
df['Star Rating Data Availability Code'].value_counts()

260.0    545
258.0    136
261.0      2
Name: Star Rating Data Availability Code, dtype: int64

### Address Line 1
Data type: object

Value count: 7626

Number of unique values: 7574

Percent unique values: 0.016553

Range of values: # 7 PROFESSIONAL DRIVE - WHEATON PARK SHOPPING CTR

Length of values: 4 - 59

Description: Lists the first line of the address that corresponds to the facility listed.

In [38]:
df['Address Line 1'].head()

0       16605 NORTH 28TH AVENUE
1                   404 CAMP RD
2                1321 S 4TH AVE
3         2235 SOUTH BABCOCK ST
4    76 HIGHLAND PAVILION COURT
Name: Address Line 1, dtype: object

In [39]:
min(set([(len(str(num))) for num in df['Address Line 1']]))

4

In [40]:
max(set([(len(str(num))) for num in df['Address Line 1']]))

59

### Address Line 2
Data type: object

Value count: 1087

Number of unique values: 599

Percent unique values: 0.001309

Length of values: 2 - 47

Description: Lists the second line of the address that corresponds to the facility listed.

In [41]:
min(set([(len(str(num))) for num in df['Address Line 2']]))

2

In [42]:
max(set([(len(str(num))) for num in df['Address Line 2']]))

47

### City
Data type: object

Value count: 7626

Number of unique values: 3001

Percent unique values: 0.006559

Range of values: ABBEVILLE - ZUNI

Length of values: 

Description: Lists the city that corresponds to the facility listed.

In [43]:
df['City'].value_counts()

HOUSTON         106
CHICAGO          77
PHILADELPHIA     55
SAN ANTONIO      53
MEMPHIS          43
               ... 
SWEENY            1
FAIRVIEW          1
FOREST CITY       1
CALEXICO          1
DONORA            1
Name: City, Length: 3009, dtype: int64

In [44]:
min(set([(len(str(num))) for num in df['City']]))

3

In [45]:
max(set([(len(str(num))) for num in df['City']]))

20

### State
Data type: object

Value count: 7626

Number of unique values: 56

Percent unique values: 0.000122

Range of values: AK - WY

Length of values: 2

Description: Lists the alphabetic postal code used to identify the state that corresponds to the facility listed.

In [46]:
df['State'].value_counts()

TX    748
CA    730
FL    510
GA    382
OH    348
IL    347
NY    332
PA    328
NC    244
MI    221
VA    212
TN    208
NJ    200
LA    189
AL    185
IN    179
MD    175
MO    164
SC    162
AZ    133
WI    129
KY    125
MN    121
WA    102
MS     92
OK     91
MA     87
CO     82
OR     75
AR     71
IA     69
KS     64
NM     58
NV     53
CT     53
PR     50
UT     48
WV     45
NE     40
DE     34
HI     33
SD     28
ID     27
DC     22
ME     20
NH     20
MT     17
RI     16
ND     15
WY     10
AK      9
VT      8
GU      5
VI      4
MP      2
AS      2
Name: State, dtype: int64

### Zip
Data type: int64

Value count: 7626

Number of unique values: 5276

Percent unique values: 0.011531

Ranges of values: 603 - 99801

Length of values: 3 - 5

Description: Lists the full postal ZIP code that corresponds to the facility listed.

In [47]:
set([(len(str(num))) for num in df['Zip']])

{3, 4, 5}

In [48]:
df['Zip'].sort_values()

628       603
723       605
1157      612
1378      612
2620      646
        ...  
894     99515
3099    99654
2787    99669
4606    99701
2011    99801
Name: Zip, Length: 7724, dtype: int64

### County
Data type: object

Value count: 7626

Number of unique values: 1258

Percent unique values: 0.002749

Range of values: ABBEVILLE - ZAVALA

Length of values: 3 - 21

Description: Lists the name of the county that corresponds to the facility listed.

In [49]:
min(set([(len(str(num))) for num in df['County']]))

3

In [50]:
max(set([(len(str(num))) for num in df['County']]))

21

### Phone Number
Data type: object

Value count: 7626

Number of unique values: 7581

Percent unique values: 0.016568

Range of values: (201) 262-0429	- (989) 921-2170

Length of values: 14

Description: Lists the telephone number that corresponds to the facility listed.

In [51]:
set([(len(str(num))) for num in df['Phone Number']])

{14}

### Profit Or Non-Profit
Data type: object

Value count: 7627

Number of unique values: 2

Percent unique values: 0.000004

Ranges of values: Non-Profit, Profit 

Length of values: 6, 10

Description: Indicates if the dialysis facility’s operates as a for profit or non-profit business.

In [52]:
df['Profit Or Non-Profit'].value_counts()

Profit        6854
Non-Profit     869
Name: Profit Or Non-Profit, dtype: int64

In [53]:
set([(len(str(num))) for num in df['Profit Or Non-Profit']])

{3, 6, 10}

### Chain Owned
Data type: object

Value count: 7626

Number of unique values: 2

Percent unique values: 0.000004

Ranges of values: No, Yes

Length of values: 2 - 3

Description: Indicates whether or not the facility is owned or managed by a chain organization.

In [54]:
df['Chain Owned'].value_counts()

Yes    6908
No      816
Name: Chain Owned, dtype: int64

### Chain Organization
Data type: object

Value count: 7625

Number of unique values: 111

Percent unique values: 0.000243

Length of values: 3 - 39

Description: Lists the name of the chain organization if applicable.

In [55]:
min(set([(len(str(num))) for num in df['Chain Organization']]))

3

In [56]:
max(set([(len(str(num))) for num in df['Chain Organization']]))

39

### Late Shift
Data type: int64

Value count: 7626

Number of unique values: 2

Percent unique values: 0.000004

Mean: 0.167060

Ranges of values: 0, 1

Length of values: 1

Description: Lists whether or not the facility has a shift starting at 5:00 p.m. or later.

In [57]:
df['Late Shift'].value_counts()

0    6443
1    1281
Name: Late Shift, dtype: int64

###  Number Of Dialysis Stations
Data type: int64

Value count: 7626

Number of unique values: 68

Percent unique values: 0.000149

Ranges of values: 0 - 80

Mean: 17.463284

Length of values: 1 - 2

Description: Indicates the total number of dialysis stations at the dialysis facility. 

### Offers In-Center Hemodialysis
Data type: int64

Value count: 7626

Number of unique values: 2

Percent unique values: 0.000004

Mean: 0.940336	

Ranges of values: 0, 1

Length of values: 1

Description: Indicates whether the facility offers in-center hemodialysis. 

In [58]:
df['Offers In-Center Hemodialysis'].value_counts()

1    7261
0     463
Name: Offers In-Center Hemodialysis, dtype: int64

### Offers Peritoneal Dialysis
Data type: int64

Value count: 7626

Number of unique values: 2

Percent unique values: 0.000004

Mean: 0.525439

Ranges of values: 0, 1

Length of values: 1

Description: Indicates whether the facility offers peritoneal dialysis.

In [59]:
df['Offers Peritoneal Dialysis'].value_counts()

1    4041
0    3683
Name: Offers Peritoneal Dialysis, dtype: int64

### Offers Home Hemodialysis Training
Data type: int64

Value count: 7626

Number of unique values: 2

Percent unique values: 0.000004

Mean: 0.29006

Ranges of values: 0, 1

Length of values: 1

Description: Indicates whether the facility offers home hemodialysis training.

In [60]:
df['Offers Home Hemodialysis Training'].value_counts()

0    5486
1    2238
Name: Offers Home Hemodialysis Training, dtype: int64

### Certification Or Recertification Date
Data type: object

Value count: 7626

Number of unique values: 4800

Percent unique values: 0.010490

Range of values: 01/01/1968 - 12/31/2017

Length of values: 10

Description: Lists the initial or recertification date for the facility listed. These facilities are certified if they pass inspection. Medicare or Medicaid only covers care provided by certified providers. Being certified is not the same as being accredited. 

In [61]:
set([(len(str(num))) for num in df['Certification Or Recertification Date']])

{10}

### Claims Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "07/01/2018 - 06/30/2019"

Length of values: 23

Description: Lists the data collection period for claims-based summaries.

In [62]:
set([(len(str(num))) for num in df['Claims Date']])

{23}

### CROWNWeb Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "07/01/2018 - 06/30/2019"

Length of values: 23

Description: Lists the data collection period for CROWNWeb based measures.

In [63]:
set([(len(str(num))) for num in df['CROWNWeb Date']])

{23}

### STrR Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "01/01/2018 - 12/31/2018"

Length of values: 23

Description: Lists the time period for patient transfusion summary (STrR).

In [64]:
set([(len(str(num))) for num in df['STrR Date']])

{23}

### Percentage Of Medicare Patients With Hgb < 10 g/dL
Data type: float64

Value count: 6517

Number of unique values: 90

Percent unique values: 0.000197

Ranges of values: 0 - 

Length of values: 1-3, 13

Description: Lists the percentage of patients who had average hemoglobin (hgb) less than 10.0 g/dL. Hemoglobin is a protein in red blood cells that carries oxygen from the lungs to the rest of the body. A normal hemoglobin level is 11 to 18 grams per deciliter (g/dL), depending on one's age and gender. But 7 to 8 g/dL is a safe level. 

In [65]:
set([(len(str(num))) for num in df['Percentage Of Medicare Patients With Hgb < 10 g/dL']])

{3, 4, 5}

### Hgb < 10 Data Availability Code
Data type: float64

Value count: 1109

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: 199, 201, 258 

Length of values: 3

Description: Lists whether the facility had sufficient hemoglobin (hgb) data available or the reason for why the data is not available. Hemoglobin is a protein in red blood cells that carries oxygen from the lungs to the rest of the body. A normal hemoglobin level is 11 to 18 grams per deciliter (g/dL), depending on one's age and gender. But 7 to 8 g/dL is a safe level. 

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure. 
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [66]:
df['Hgb < 10 Data Availability Code'].value_counts()

199.0    603
258.0    377
201.0    105
Name: Hgb < 10 Data Availability Code, dtype: int64

### Percentage Of Medicare Patients With Hgb > 12 g/dL
Data type: float64

Value count: 6517

Number of unique values: 20

Percent unique values: 0.000044

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the percentage of patients who had average hemoglobin (hgb) greater than 12.0 g/dL. Hemoglobin is a protein in red blood cells that carries oxygen from the lungs to the rest of the body. A normal hemoglobin level is 11 to 18 grams per deciliter (g/dL), depending on one's age and gender. But 7 to 8 g/dL is a safe level. 

In [67]:
set([(len(str(num))) for num in df['Percentage Of Medicare Patients With Hgb > 12 g/dL']])

{3, 4}

### Hgb > 12 Data Availability Code
Data type: float64

Value count: 1109

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: 199, 201, 258

Length of values: 3

Description: Lists whether the facility had sufficient hemoglobin (hgb) data available or the reason for why the data is not available. Hemoglobin is a protein in red blood cells that carries oxygen from the lungs to the rest of the body. A normal hemoglobin level is 11 to 18 grams per deciliter (g/dL), depending on one's age and gender. But 7 to 8 g/dL is a safe level. 

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure. 
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [68]:
df['Hgb > 12 Data Availability Code'].value_counts()

199.0    603
258.0    377
201.0    105
Name: Hgb > 12 Data Availability Code, dtype: int64

### Number Of Dialysis Patients With Hgb Data
Data type: float64

Value count: 7555

Number of unique values: 159

Percent unique values: 0.000347

Ranges of values: 0 - 

Length of values: 1-3

Description: Lists the number of patients included in the hemoglobin (hgb) greater than 12.0 g/dL summary. Hemoglobin is a protein in red blood cells that carries oxygen from the lungs to the rest of the body. A normal hemoglobin level is 11 to 18 grams per deciliter (g/dL), depending on one's age and gender. But 7 to 8 g/dL is a safe level. 

In [69]:
set([(len(str(num))) for num in df['Number Of Dialysis Patients With Hgb Data']])

{3, 4, 5}

### Patient Transfusion Data Availability Code
Data type: float64

Value count: 1341

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 199, 201, 255, 258

Length of values: 3

Description: Lists whether the facility had sufficient transfusion data available or the reason for why the data is not available.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure. 
- 255 : Medicare determined that the percentage reported was not accurate.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [70]:
df['Patient Transfusion Data Availability Code'].value_counts()

199.0    721
258.0    406
201.0     32
255.0      1
Name: Patient Transfusion Data Availability Code, dtype: int64

### Patient Transfusion Category Text
Data type: object

Value count: 6285

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: As Expected, Not Available, Worse than Expected, Better than Expected 

Length of values: 3, 11, 19, 20

Description: Patient transfusion category.

Value description:
- As Expected          : Patient transfusions categorized as “As Expected”       
- Worse than Expected  :  Patient transfusions categorized as “Worse than Expected”
- Better than Expected : Patient transfusions categorized as “Better than Expected"
- Not Available 

In [71]:
df['Patient Transfusion Category Text'].value_counts()

As Expected             6108
Worse than Expected      448
Better than Expected       8
Name: Patient Transfusion Category Text, dtype: int64

In [72]:
set([(len(str(num))) for num in df['Patient Transfusion Category Text']])

{3, 11, 19, 20}

### Number Of Patients Included In The Transfusion Summary
Data type: float64

Value count: 7552

Number of unique values: 225

Percent unique values: 0.000492

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of patients included in the facility’s transfusion summary.

In [73]:
set([(len(str(num))) for num in df['Number Of Patients Included In The Transfusion Summary']])

{3, 4, 5}

### Percent Of Adult HD Patients With Kt/V >= 1.2
Data type: float64

Value count: 6755

Number of unique values: 53

Percent unique values: 0.000116 

Ranges of values: 0 - 

Length of values: 1 - 3, 13

Description: Lists the percentage of adult HD patients with Kt/V greater than or equal to 1.2. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [74]:
set([(len(str(num))) for num in df['Percent Of Adult HD Patients With Kt/V >= 1.2']])

{3, 4, 5}

### Adult HD Kt/V Data Availability Code
Data type: float64

Value count: 871

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 1, 199, 201, 256, 258

Length of values: 1, 3

Description: Lists whether the facility had sufficient adult HD Kt/V data available or the reason for why the data is not available. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

Value description: 
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 256 : The dialysis center does not provide hemodialysis during the reporting period. 
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [75]:
df['Adult HD Kt/V Data Availability Code'].value_counts()

199.0    308
258.0    284
201.0    140
256.0    137
255.0      1
Name: Adult HD Kt/V Data Availability Code, dtype: int64

### Percentage Of Adult PD PTS With Kt/V >= 1.7
Data type: float64

Value count: 2146

Number of unique values: 70

Percent unique values: 0.000153

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the percentage of adult PD PTS patients with Kt/V greater than or equal to 1.7. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [76]:
set([(len(str(num))) for num in df['Percentage Of Adult PD PTS With Kt/V >= 1.7']])

{3, 4, 5}

### Adult PD Kt/V Data Availability Code
Data type: float64 

Value count: 5480

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 1, 199, 201, 257, 258

Length of values: 1, 3

Description: Lists whether the facility had sufficient adult PD Kt/V data available or the reason for why the data is not available. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 257 : The dialysis center does not provide peritoneal dialysis during the reporting period. 
- 258 : The dialysis center was not open long enough to supply sufficient measure data.

In [77]:
df['Adult PD Kt/V Data Availability Code'].value_counts()

257.0    3393
199.0    1127
201.0     794
258.0     195
255.0       1
Name: Adult PD Kt/V Data Availability Code, dtype: int64

### Percentage Of Pediatric HD Patients With Kt/V >= 1.2
Data type: float64

Value count: 16

Number of unique values: 11

Percent unique values: 0.000024

Ranges of values: 100 - 

Length of values: 2, 3

Description: Lists the percentage of pediatric HD patients with Kt/V greater than or equal to 1.2. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [78]:
set([(len(str(num))) for num in df['Percentage Of Pediatric HD Patients With Kt/V >= 1.2']])

{3, 4, 5}

### Pediatric HD Kt/V Data Availability Code
Data type: float64

Value count: 7610

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 199, 201, 258, 259

Length of values: 3

Description: Lists whether the facility had sufficient Pediatric HD Kt/V data available or the reason for why the data is not available. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment(characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 
- 259 : The dialysis center does not provide hemodialysis and/or peritoneal dialysis to pediatric patients during the reporting period.

In [79]:
df['Pediatric HD Kt/V Data Availability Code'].value_counts()

259.0    7176
201.0     238
199.0     181
258.0     115
Name: Pediatric HD Kt/V Data Availability Code, dtype: int64

### Number Of Adult HD Patients With Kt/V Data
Data type: float64

Value count: 7555

Number of unique values: 270

Percent unique values: 0.000590

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of adult HD patients included in Kt/V greater than or equal to 1.2 summary. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [80]:
set([(len(str(num))) for num in df['Number Of Adult HD Patients With Kt/V Data']])

{3, 4, 5}

### Number Of Adult HD Patient-Months With Kt/V Data
Data type: float64

Value count: 7175

Number of unique values: 1629

Percent unique values: 0.003560

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the number of adult HD patient-months included in Kt/V greater than or equal to 1.2 summary. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [81]:
set([(len(str(num))) for num in df['Number Of Adult HD Patient-Months With Kt/V Data']])

{3, 4, 5, 6}

### Number Of Adult PD Patients With Kt/V Data
Data type: float64

Value count: 7555

Number of unique values: 136

Percent unique values: 0.000297

Ranges of values: 0 -

Length of values: 1 - 3, 13

Description: Lists the number of adult PD patients included in Kt/V greater than or equal to 1.7 summary. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [82]:
set([(len(str(num))) for num in df['Number Of Adult PD Patients With Kt/V Data']])

{3, 4, 5}

### Number Of Adult PD Patient-Months With Kt/V Data
Data type: float64

Value count: 3358

Number of unique values: 610

Percent unique values: 0.001333

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the number of adult PD patient-months included in Kt/V greater than or equal to 1.7 summary. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered). 

In [83]:
set([(len(str(num))) for num in df['Number Of Adult PD Patient-Months With Kt/V Data']])

{3, 4, 5, 6}

### Number Of Pediatric HD Patients With Kt/V Data
Data type: float64

Value count: 7555

Number of unique values: 19

Percent unique values: 0.000042

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of pediatric HD patients included in Kt/V greater than or equal to 1.2 summary. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [84]:
set([(len(str(num))) for num in df['Number Of Pediatric HD Patients With Kt/V Data']])

{3, 4}

### Number Of Pediatric HD Patient-Months With Kt/V Data
Data type: float64 

Value count: 202

Number of unique values: 67

Percent unique values: 0.000146

Ranges of values: 1 - 

Length of values: 1 - 3

Description: Lists the number of pediatric HD patientmonths included in Kt/V greater than or equal to 1.2 summary. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [85]:
set([(len(str(num))) for num in df['Number Of Pediatric HD Patient-Months With Kt/V Data']])

{3, 4, 5}

### Hypercalcemia Data Availability Code
Data type: float64

Value count: 422

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: 199, 201, 258

Length of values: 3

Description: Lists whether the facility had sufficient hypercalcemia data available or the reason for why the data is not available. Hypercalcemia is a condition in which the calcium level in one's blood is above normal. Too much calcium in the blood can weaken bones, create kidney stones, and interfere with how the heart and brain work. Hypercalcemia is usually a result of overactive parathyroid glands.
A normal serum calcium level is 8-10 mg/dL (2-2.5 mmol/L) with some interlaboratory variation in the reference range, and hypercalcemia is defined as a serum calcium level greater than 10.5 mg/dL (>2.5 mmol/L).

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [86]:
df['Hypercalcemia Data Availability Code'].value_counts()

258.0    270
199.0    132
201.0     21
255.0      2
Name: Hypercalcemia Data Availability Code, dtype: int64

### Number Of Patients In Hypercalcemia Summary
Data type: float64

Value count: 7555

Number of unique values: 310

Percent unique values: 0.000678

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of patients included in the facility’s hypercalcemia summary. Hypercalcemia is a condition in which the calcium level in one's blood is above normal. Too much calcium in the blood can weaken bones, create kidney stones, and interfere with how the heart and brain work. Hypercalcemia is usually a result of overactive parathyroid glands.
A normal serum calcium level is 8-10 mg/dL (2-2.5 mmol/L) with some interlaboratory variation in the reference range, and hypercalcemia is defined as a serum calcium level greater than 10.5 mg/dL (>2.5 mmol/L).

In [87]:
set([(len(str(num))) for num in df['Number Of Patients In Hypercalcemia Summary']])

{3, 4, 5}

### Number Of Patient-Months In Hypercalcemia Summary
Data type: float64

Value count: 7463

Number of unique values: 1865

Percent unique values: 0.004076

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the number of patient-months included in the facility’s hypercalcemia summary. Hypercalcemia is a condition in which the calcium level in one's blood is above normal. Too much calcium in the blood can weaken bones, create kidney stones, and interfere with how the heart and brain work. Hypercalcemia is usually a result of overactive parathyroid glands.
A normal serum calcium level is 8-10 mg/dL (2-2.5 mmol/L) with some interlaboratory variation in the reference range, and hypercalcemia is defined as a serum calcium level greater than 10.5 mg/dL (>2.5 mmol/L).

In [88]:
set([(len(str(num))) for num in df['Number Of Patient-Months In Hypercalcemia Summary']])

{3, 4, 5, 6}

### Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 mg/dL)
Data type: float64

Value count: 7204

Number of unique values: 48

Percent unique values: 0.000105

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the percentage of Adult patients with Hypercalcemia (serum calcium greater than 10.2 mg/dL). Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders. 

In [89]:
set([(len(str(num))) for num in df['Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 mg/dL)']])

{3, 4}

### Number Of Patients In Serum Phosphorus Summary
Data type: float64

Value count: 7555

Number of unique values: 323

Percent unique values: 0.000706

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of patients included in the facility’s serum phosphorus summary.
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

In [90]:
set([(len(str(num))) for num in df['Number Of Patients In Serum Phosphorus Summary']])

{3, 4, 5}

### Number Of Patient-Months In Serum Phosphorus Summary
Data type: float64

Value count: 7463

Number of unique values: 1903

Percent unique values: 0.004159

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the number of patient-months included in the facility’s serum phosphorus summary.
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

In [91]:
set([(len(str(num))) for num in df['Number Of Patient-Months In Serum Phosphorus Summary']])

{3, 4, 5, 6}

### Serum Phosphorus Data Availability Code 
Data type: float64

Value count: 411

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: 199, 201, 258

Length of values: 3

Description: Lists whether the facility had sufficient serum phosphorus data available or the reason for why the data is not available.
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [92]:
df['Serum Phosphorus Data Availability Code'].value_counts()

258.0    265
199.0    124
201.0     25
Name: Serum Phosphorus Data Availability Code, dtype: int64

### Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 mg/dL
Data type: float64

Value count: 7215

Number of unique values: 35

Percent unique values:  0.000076

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the percentage of Adult patients with serum phosphorus less than 3.5 mg/dL.
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

In [93]:
set([(len(str(num))) for num in df['Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 mg/dL']])

{3, 4}

### Percentage Of Adult Patients With Serum Phosphorus Between 3.5 - 4.5 mg/dL
Data type: float64

Value count: 7215

Number of unique values: 46

Percent unique values: 0.000101

Ranges of values: 10 - 

Length of values: 1 - 3

Description: Lists the percentage of Adult patients with serum phosphorus between 3.5-4.5 mg/dL.
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

In [94]:
set([(len(str(num))) for num in df['Percentage Of Adult Patients With Serum Phosphorus Between 3.5 - 4.5 mg/dL']])

{3, 4}

### Percentage Of Adult Patients With Serum Phosphorus Between 4.6 - 5.5 mg/dL
Data type: float64

Value count: 7215

Number of unique values: 44

Percent unique values: 0.000096

Ranges of values: 12 - 

Length of values: 1 - 3

Description: Lists the percentage of Adult patients with serum phosphorus between 4.6-5.5 mg/dL.
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

In [95]:
set([(len(str(num))) for num in df['Percentage Of Adult Patients With Serum Phosphorus Between 4.6 - 5.5 mg/dL']])

{3, 4}

### Percentage Of Adult Patients With Serum Phosphorus Between 5.6 - 7.0 mg/dL
Data type: float64

Value count: 7215

Number of unique values: 44

Percent unique values: 0.000096

Ranges of values: 10 - 

Length of values: 1 - 3

Description: Lists the percentage of Adult patients with serum phosphorus between 5.6-7.0 mg/dL.
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

In [96]:
set([(len(str(num))) for num in df['Percentage Of Adult Patients With Serum Phosphorus Between 5.6 - 7.0 mg/dL']])

{3, 4}

### Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 mg/dL
Data type: float64

Value count: 7215

Number of unique values: 40

Percent unique values: 0.000087

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the percentage of Adult patients with serum phosphorus greater than 7.0 mg/dL.
Serum phosphorus is measured in milligrams of phosphorus per deciliter of blood (mg/dL). According to Mayo Medical Laboratories, a normal range for adults is generally 2.5 to 4.5 mg/dL. The normal range varies slightly depending on your age.
Most commonly, a high level of phosphorus is related to a kidney disorder. It shows that your kidneys are having difficulty clearing phosphorus from your blood. A high level of phosphorus can also mean uncontrolled diabetes and other endocrine disorders.

In [97]:
set([(len(str(num))) for num in df['Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 mg/dL']])

{3, 4}

### SHR Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "01/01/2018 - 12/31/2018"

Length of values: 23

Description: Lists the time period for patient hospitalization summary.

In [98]:
df['SHR Date'].value_counts()

01/01/2019 - 12/31/2019    7724
Name: SHR Date, dtype: int64

In [99]:
set([(len(str(num))) for num in df['SHR Date']])

{23}

### SRR Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "01/01/2018 - 12/31/2018"

Length of values: 23

Description: Lists the time period for patient readmission summary.

In [100]:
df['SRR Date'].value_counts()

01/01/2019 - 12/31/2019    7724
Name: SRR Date, dtype: int64

In [101]:
set([(len(str(num))) for num in df['SRR Date']])

{23}

### SMR Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "01/01/2015 - 12/31/2018"

Length of values: 23

Description: Lists the data collection period for patient survival summary.

In [102]:
df['SMR Date'].value_counts()

01/01/2016 - 12/31/2019    7724
Name: SMR Date, dtype: int64

In [103]:
set([(len(str(num))) for num in df['SRR Date']])

{23}

### Patient Hospitalization Category Text
Data type: object

Value count: 6857

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: As Expected, Not Available, Worse than Expected, Better than Expected

Length of values: 3, 11, 19, 20

Description: Patient hospitalization category.

In [104]:
df['Patient Hospitalization Category Text'].value_counts()

As Expected             6818
Worse than Expected      295
Better than Expected      72
Name: Patient Hospitalization Category Text, dtype: int64

In [105]:
set([(len(str(num))) for num in df['Patient Hospitalization Category Text']])

{3, 11, 19, 20}

### Patient Hospitalization Data Availability Code
Data type: float64

Value count: 769

Number of unique values: 4

Percent unique values: 0.000009 

Ranges of values: 199, 201, 255, 258

Length of values: 3

Description: Lists whether the facility had sufficient hospitalization data available or the reason for why the data is not available.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 255 : Medicare determined that the percentage reported was not accurate.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [106]:
df['Patient Hospitalization Data Availability Code'].value_counts()

258.0    358
199.0    163
201.0     16
255.0      2
Name: Patient Hospitalization Data Availability Code, dtype: int64

### Patient Hospital Readmission Category
Data type: object

Value count: 6806

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: As Expected, Not Available, Worse than Expected, Better than Expected

Length of values: 3, 11, 19, 20

Description: Patient readmission category.

Value description:
- As Expected          : Patient hospital readmission categorized as “As Expected”       
- Worse than Expected  :  Patient hospital readmission categorized as “Worse than Expected”
- Better than Expected : Patient hospital readmission categorized as “Better than Expected"

In [107]:
df['Patient Hospital Readmission Category Text'].value_counts()

As Expected             6714
Worse than Expected      250
Better than Expected     154
Name: Patient Hospital Readmission Category Text, dtype: int64

In [108]:
set([(len(str(num))) for num in df['Patient Hospital Readmission Category Text']])

{3, 11, 19, 20}

### Patient Hospital Readmission Data Availability Code
Data type: float64

Value count: 820

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: 199, 255, 258

Length of values: 3

Description: Lists whether the facility had sufficient readmission data available or the reason for why the data is not available.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 255 : Medicare determined that the percentage reported was not accurate.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [109]:
df['Patient Hospital Readmission Data Availability Code'].value_counts()

258.0    334
199.0    271
255.0      1
Name: Patient Hospital Readmission Data Availability Code, dtype: int64

### Patient Survival Category Text
Data type: object

Value count: 6701

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: As Expected, Worse than Expected, Better than Expected

Length of values: 3, 11, 19, 20

Description: Patient survival category (Better, Worse or As Expected).

Value description:
- As Expected          : Patient transfusions categorized as “As Expected”       
- Worse than Expected  :  Patient transfusions categorized as “Worse than Expected”
- Better than Expected : Patient transfusions categorized as “Better than Expected"

In [110]:
df['Patient Survival Category Text'].value_counts()

As Expected             5966
Better than Expected     561
Worse than Expected      485
Name: Patient Survival Category Text, dtype: int64

In [111]:
set([(len(str(num))) for num in df['Patient Hospital Readmission Category Text']])

{3, 11, 19, 20}

### Patient Survival Data Availability Code
Data type: float64

Value count: 925

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 199, 201, 255, 258

Length of values: 3 

Description: Lists whether the facility had sufficient patient survival data available or the reason for why the data is not available.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 255 : Medicare determined that the percentage reported was not accurate.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [112]:
df['Patient Survival Data Availability Code'].value_counts()

258.0    401
199.0    300
201.0      9
255.0      2
Name: Patient Survival Data Availability Code, dtype: int64

### Number Of Patients Included In Hospitalization Summary
Data type: float64

Value count: 7552

Number of unique values: 249

Percent unique values: 0.000553

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of patients included in the facility’s hospitalization summary.

In [113]:
set([(len(str(num))) for num in df['Number Of Patients Included In Hospitalization Summary']])

{3, 4, 5}

### Number Of Hospitalizations Included In Hospital Readmission Summary
Data type: float64

Value count: 7553

Number of unique values: 295

Percent unique values: 0.000656

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of index discharges included in the facility’s readmission summary.

In [114]:
set([(len(str(num))) for num in df['Number Of Hospitalizations Included In Hospital Readmission Summary']])

{3, 4, 5}

### Number Of Patients Included In Survival Summary
Data type: float64

Value count: 7552

Number of unique values: 807

Percent unique values: 0.001794

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the number of patients included in the facility’s survival summary.

In [115]:
set([(len(str(num))) for num in df['Number Of Patients Included In Survival Summary']])

{3, 4, 5, 6}

### Mortality Rate (Facility)
Data type: float64

Value count: 6701

Number of unique values: 390

Percent unique values: 0.000867

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the facility’s mortality rate per 100 patient-years.

In [116]:
set([(len(str(num))) for num in df['Mortality Rate (Facility)']])

{3, 4}

### Mortality Rate: Upper Confidence Limit (97.5%)
Data type: float64

Value count: 6701

Number of unique values: 545

Percent unique values: 0.001211

Ranges of values: 10.3 -

Length of values: 2 - 5

Description: Lists the upper confident limit (97.5%) for mortality rate per 100 patient-years.

In [117]:
set([(len(str(num))) for num in df['Mortality Rate: Upper Confidence Limit (97.5%)']])

{3, 4, 5}

### Mortality Rate: Lower Confidence Limit (2.5%)
Data type: float64

Value count: 6701

Number of unique values: 323

Percent unique values: 0.000718

Ranges of values: 0.1 - 

Length of values: 1 - 4

Description: Lists the lower confident limit (2.5%) for mortality rate per 100 patient-years.

In [118]:
set([(len(str(num))) for num in df['Mortality Rate: Lower Confidence Limit (2.5%)']])

{3, 4}

### Readmission Rate (Facility)
Data type: float64

Value count: 6806

Number of unique values: 463

Percent unique values: 0.001029

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the facility’s readmission rate as a percentage of hospital discharges.

In [119]:
set([(len(str(num))) for num in df['Readmission Rate (Facility)']])

{3, 4}

### Readmission Rate: Upper Confidence Limit (97.5%)
Data type: float64

Value count: 6806

Number of unique values: 543

Percent unique values: 0.001207

Ranges of values: 104.2

Length of values: 2 - 5

Description: Lists the upper confident limit (97.5%) for readmission rate as a percentage of hospital discharges.

In [120]:
set([(len(str(num))) for num in df['Readmission Rate: Upper Confidence Limit (97.5%)']])

{3, 4, 5}

### Readmission Rate: Lower Confidence Limit (2.5%)
Data type: float64

Value count: 6806

Number of unique values: 338

Percent unique values: 0.000751

Ranges of values: 0.1 - 

Length of values: 1 - 4

Description: Lists the lower confident limit (2.5%) for readmission rate as a percentage of hospital discharges.

In [121]:
set([(len(str(num))) for num in df['Readmission Rate: Lower Confidence Limit (2.5%)']])

{3, 4}

### Hospitalization Rate (Facility)
Data type: float64

Value count: 6857

Number of unique values: 2004

Percent unique values: 0.004454

Ranges of values: 0 - 

Length of values: 1 - 5

Description: Lists the facility’s hospitalization rate per 100 patient-years.

In [122]:
set([(len(str(num))) for num in df['Hospitalization Rate (Facility)']])

{3, 4, 5}

### Hospitalization Rate: Upper Confidence Limit (97.5%)
Data type: float64

Value count: 6856

Number of unique values: 2583

Percent unique values: 0.005741

Ranges of values: 1079.9 - 

Length of values: 3, 5, 6

Description: Lists the upper confident limit (97.5%) for hospitalization rate per 100 patient-years.

In [123]:
set([(len(str(num))) for num in df['Hospitalization Rate: Upper Confidence Limit (97.5%)']])

{3, 5}

### Hospitalization Rate: Lower Confidence Limit (2.5%)
Data type: float64

Value count: 6857

Number of unique values: 1710

Percent unique values: 0.003801

Ranges of values: 0 -

Length of values: 1 - 5

Description: Lists the lower confident limit (2.5%) for hospitalization rate per 100 patient-years.

In [124]:
set([(len(str(num))) for num in df['Hospitalization Rate: Lower Confidence Limit (2.5%)']])

{3, 4, 5}

### Number Of Pediatric PD Patients With Kt/V Data
Data type: float64

Value count: 7555

Number of unique values: 25

Percent unique values: 0.000056

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of pediatric PD patients included in Kt/V greater than or equal to 1.8 summary. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [125]:
set([(len(str(num))) for num in df['Number Of Pediatric PD Patients With Kt/V Data']])

{3, 4}

### Pediatric PD Kt/V Data Availability Code
Data type: float64 

Value count: 7597

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 199, 201, 258, 259

Length of values: 3

Description: Lists whether the facility had sufficient pediatric PD Kt/V data available or the reason for why the data is not available. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 
- 259 : The dialysis center does not provide hemodialysis and/or peritoneal dialysis to pediatric patients during the reporting period.

In [126]:
df['Pediatric PD Kt/V Data Availability Code'].value_counts()

259.0    7311
201.0     151
199.0     124
258.0     110
Name: Pediatric PD Kt/V Data Availability Code, dtype: int64

### Number Of Pediatric PD Patient-Months With Kt/V Data
Data type: float64

Value count: 150

Number of unique values: 81

Percent unique values: 0.000180

Ranges of values: 1 - 

Length of values: 1 - 3

Description: Lists the number of pediatric PD patient months included in Kt/V greater than or equal to 1.8 summary. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [127]:
set([(len(str(num))) for num in df['Number Of Pediatric PD Patient-Months With Kt/V Data']])

{3, 4, 5}

### Percentage Of Pediatric PD Patients With Kt/V >= 1.8
Data type: float64

Value count: 29

Number of unique values: 21

Percent unique values: 0.000047

Ranges of values: 23 - 

Length of values: 2, 3

Description: Lists the percentage of pediatric PD patients with Kt/V greater than or equal to 1.8. The parameter Kt/V is a measurement of the efficacy of a hemodialysis session. It identifies the effective removal of a specific solute (clearance K) resulting from a given treatment (characterized by time t) in a given patient (with a specific volume of distribution V for the solute considered).

In [128]:
set([(len(str(num))) for num in df['Percentage Of Pediatric PD Patients With Kt/V >= 1.8']])

{3, 4, 5}

### SIR Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "01/01/2018 - 12/31/2018"

Length of values: 23

Description: Lists the time period for patient infection summary (SIR).

In [129]:
df['SIR Date'].value_counts()

01/01/2019 - 12/31/2019    7724
Name: SIR Date, dtype: int64

In [130]:
set([(len(str(num))) for num in df['SIR Date']])

{23}

### Patient Infection Data Availability Code
Data type: float64

Value count: 1375

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: 199, 201, 258

Length of values: 3

Description: Lists whether the facility had sufficient infection data available or the reason for why the data is not available.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [131]:
df['Patient Infection Data Availability Code'].value_counts()

201.0    709
258.0    393
199.0    121
Name: Patient Infection Data Availability Code, dtype: int64

### Patient Infection Category Text
Data type: object

Value count: 6251

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: As Expected, Worse than Expected, Better than Expected

Length of values: 3, 11, 19, 20

Description: Patient infection category.

Value description:
- As Expected          : Patient infection categorized as “As Expected”       
- Worse than Expected  :  Patient infection categorized as “Worse than Expected”
- Better than Expected : Patient infection categorized as “Better than Expected"

In [132]:
df['Patient Infection Category Text'].value_counts()

As Expected             5011
Better than Expected    1328
Worse than Expected      162
Name: Patient Infection Category Text, dtype: int64

In [133]:
set([(len(str(num))) for num in df['Patient Infection Category Text']])

{3, 11, 19, 20}

### Standard Infection Ratio
Data type: float64

Value count: 6251

Number of unique values: 336

Percent unique values: 0.000747

Ranges of values: 0.5 - 

Length of values: 1 - 5

Description: Lists the facility’s Standardized Infection Ratio.

In [134]:
set([(len(str(num))) for num in df['Standard Infection Ratio']])

{3, 4}

### SIR: Upper Confidence Limit (97.5%)
Data type: float64

Value count: 6251

Number of unique values: 602

Percent unique values: 0.001338

Ranges of values: 0.16 - 

Length of values: 1 - 5

Description: Lists the upper confident limit (97.5%) for Standardized Infection Ratio (SIR).

In [135]:
set([(len(str(num))) for num in df['SIR: Upper Confidence Limit (97.5%)']])

{3, 4, 5}

### SIR: Lower Confidence Limit (2.5%)
Data type: float64

Value count: 5368

Number of unique values: 190

Percent unique values: 0.000422

Ranges of values: 0.01 - 

Length of values: 1 - 4

Description: Lists the lower confident limit (2.5%) for Standardized Infection Ratio (SIR).

In [136]:
set([(len(str(num))) for num in df['SIR: Lower Confidence Limit (2.5%)']])

{3, 4}

### Transfusion Rate (Facility)
Data type: float64

Value count: 6285

Number of unique values: 717

Percent unique values: 0.001594

Ranges of values: 0 - 

Length of values: 1 - 5

Description: Lists the facility’s transfusion rate per 100 patient-years.

In [137]:
set([(len(str(num))) for num in df['Transfusion Rate (Facility)']])

{3, 4, 5}

### Transfusion Rate: Upper Confidence Limit (97.5%)
Data type: float64

Value count: 6285

Number of unique values: 1604

Percent unique values: 0.003565 

Ranges of values: 100 - 

Length of values: 2 - 5

Description: Lists the upper confident limit (97.5%) for transfusion rate per 100 patient-years.

In [138]:
set([(len(str(num))) for num in df['Transfusion Rate: Upper Confidence Limit (97.5%)']])

{3, 4, 5}

### Transfusion Rate: Lower Confidence Limit (2.5%)
Data type: float64

Value count: 6285

Number of unique values: 413

Percent unique values: 0.000918

Ranges of values: 0.1 - 

Length of values: 1 - 5

Description: Lists the lower confident limit (2.5%) for transfusion rate per 100 patient-years.

In [139]:
set([(len(str(num))) for num in df['Transfusion Rate: Lower Confidence Limit (2.5%)']])

{3, 4, 5}

### Fistula Data Availability Code
Data type: float64

Value count: 711

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 199, 201, 256, 258

Length of values: 3

Description: Lists whether the facility had sufficient fistula data available or the reason for why the data is not available. The best type of long-term access is an AV fistula. A surgeon connects an artery to a vein, usually in your arm, to create an AV fistula. An artery is a blood vessel that carries blood away from your heart. A vein is a blood vessel that carries blood back toward your heart. When the surgeon connects an artery to a vein, the vein grows wider and thicker, making it easier to place the needles for dialysis. The AV fistula also has a large diameter that allows your blood to flow out and back into your body quickly. The goal is to allow high blood flow so that the largest amount of blood can pass through the dialyzer.

Value description: 
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 256 : The dialysis center does not provide hemodialysis during the reporting period. 
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [140]:
df['Fistula Data Availability Code'].value_counts()

258.0    274
199.0    261
256.0    113
201.0     57
255.0      2
Name: Fistula Data Availability Code, dtype: int64

### Fistula Category Text
Data type: object

Value count: 6915

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: As Expected, Worse than Expected, Better than Expected

Length of values: 3, 11, 19, 20

Description: Fistula category. The best type of long-term access is an AV fistula. A surgeon connects an artery to a vein, usually in your arm, to create an AV fistula. An artery is a blood vessel that carries blood away from your heart. A vein is a blood vessel that carries blood back toward your heart. When the surgeon connects an artery to a vein, the vein grows wider and thicker, making it easier to place the needles for dialysis. The AV fistula also has a large diameter that allows your blood to flow out and back into your body quickly. The goal is to allow high blood flow so that the largest amount of blood can pass through the dialyzer.

Value description:
- As Expected          : Patient fistulas categorized as “As Expected”       
- Worse than Expected  :  Patient fistulas categorized as “Worse than Expected”
- Better than Expected : Patient fistulas categorized as “Better than Expected"

In [141]:
df['Fistula Category Text'].value_counts()

As Expected             6517
Better than Expected     290
Worse than Expected      210
Name: Fistula Category Text, dtype: int64

In [142]:
set([(len(str(num))) for num in df['Fistula Category Text']])

{3, 11, 19, 20}

### Number Of Patients Included In Fistula Summary
Data type: float64

Value count: 7555

Number of unique values: 292

Percent unique values: 0.000649

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of patients included in the facility’s fistula summary. The best type of long-term access is an AV fistula. A surgeon connects an artery to a vein, usually in your arm, to create an AV fistula. An artery is a blood vessel that carries blood away from your heart. A vein is a blood vessel that carries blood back toward your heart. When the surgeon connects an artery to a vein, the vein grows wider and thicker, making it easier to place the needles for dialysis. The AV fistula also has a large diameter that allows your blood to flow out and back into your body quickly. The goal is to allow high blood flow so that the largest amount of blood can pass through the dialyzer.

In [143]:
set([(len(str(num))) for num in df['Number Of Patients Included In Fistula Summary']])

{3, 4, 5}

### Fistula Rate (Facility)
Data type: float64

Value count: 6915

Number of unique values: 587

Percent unique values: 0.001305

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the facility’s fistula rate per 100 patient-years. The best type of long-term access is an AV fistula. A surgeon connects an artery to a vein, usually in your arm, to create an AV fistula. An artery is a blood vessel that carries blood away from your heart. A vein is a blood vessel that carries blood back toward your heart. When the surgeon connects an artery to a vein, the vein grows wider and thicker, making it easier to place the needles for dialysis. The AV fistula also has a large diameter that allows your blood to flow out and back into your body quickly. The goal is to allow high blood flow so that the largest amount of blood can pass through the dialyzer.

In [144]:
set([(len(str(num))) for num in df['Fistula Rate (Facility)']])

{3, 4, 5}

### Fistula Rate: Upper Confidence Limit (97.5%)
Data type: float64

Value count: 6915

Number of unique values: 487

Percent unique values: 0.001082

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the upper confident limit (97.5%) for fistula rate per 100 patient-years. The best type of long-term access is an AV fistula. A surgeon connects an artery to a vein, usually in your arm, to create an AV fistula. An artery is a blood vessel that carries blood away from your heart. A vein is a blood vessel that carries blood back toward your heart. When the surgeon connects an artery to a vein, the vein grows wider and thicker, making it easier to place the needles for dialysis. The AV fistula also has a large diameter that allows your blood to flow out and back into your body quickly. The goal is to allow high blood flow so that the largest amount of blood can pass through the dialyzer.

In [145]:
set([(len(str(num))) for num in df['Fistula Rate: Upper Confidence Limit (97.5%)']])

{3, 4, 5}

### Fistula Rate: Lower Confidence Limit (2.5%)
Data type: float64

Value count: 6915

Number of unique values: 727

Percent unique values: 0.001616

Ranges of values: 0.1 - 

Length of values: 1 - 4

Description: Lists the lower confident limit (2.5%) for fistula rate per 100 patient-years. The best type of long-term access is an AV fistula. A surgeon connects an artery to a vein, usually in your arm, to create an AV fistula. An artery is a blood vessel that carries blood away from your heart. A vein is a blood vessel that carries blood back toward your heart. When the surgeon connects an artery to a vein, the vein grows wider and thicker, making it easier to place the needles for dialysis. The AV fistula also has a large diameter that allows your blood to flow out and back into your body quickly. The goal is to allow high blood flow so that the largest amount of blood can pass through the dialyzer.

In [146]:
set([(len(str(num))) for num in df['Fistula Rate: Lower Confidence Limit (2.5%)']])

{3, 4, 5}

### Number Of Patients In Long Term Catheter Summary
Data type: float64

Value count: 7555

Number of unique values: 292

Percent unique values: 0.000649

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of patients included in the facility’s long term catheter summary. 

In [147]:
set([(len(str(num))) for num in df['Number Of Patients In Long Term Catheter Summary']])

{3, 4, 5}

### Number Of Patient-Months In Long Term Catheter Summary
Data type: float64

Value count: 7298

Number of unique values: 1780

Percent unique values: 0.003956

Ranges of values: 1 - 

Length of values: 1 - 4

Description: Lists the number of patient-months included in the facility’s long term catheter summary. 

In [148]:
set([(len(str(num))) for num in df['Number Of Patient-Months In Long Term Catheter Summary']])

{3, 4, 5, 6}

### Long Term Catheter Data Availability Code
Data type: float64

Value count: 711

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 199, 201, 256, 258

Length of values: 3

Description: Lists whether the facility had sufficient long term catheter data available or the reason for why the data is not available.

Value description: 
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 256 : The dialysis center does not provide hemodialysis during the reporting period. 
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 

In [149]:
df['Long Term Catheter Data Availability Code'].value_counts()

258.0    264
199.0    261
256.0    123
201.0     57
255.0      2
Name: Long Term Catheter Data Availability Code, dtype: int64

### Percentage Of Adult Patients With Long Term Catheter In Use
Data type: float64

Value count: 6915

Number of unique values: 67

Percent unique values: 0.000149

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the percentage of adult patients with long term catheter in use.

In [150]:
set([(len(str(num))) for num in df['Percentage Of Adult Patients With Long Term Catheter In Use']])

{3, 4}

### Number Of Patients In nPCR Summary
Data type: float64

Value count: 7555 

Number of unique values: 25

Percent unique values: 0.000056

Ranges of values: 0 - 

Length of values: 1 - 3

Description: 
Lists the number of patients included in the facility's normalized protein catabolic rate (nPCR) summary. The normalized protein catabolic rate (nPCR) is a formula commonly used to assess dietary protein intake in dialysis patients, as a means towards determining nutritional adequacy, a major problem in many ESRD patients. 
The nPCR is reported in grams of urea nitrogen per kilogram per day.
Most guidelines specify maintaining the protein intake above 1.0 – 1.2 g/kg/day in dialysis patients, with values less than 0.8 g/kg/day being equated with malnutrition.

In [151]:
set([(len(str(num))) for num in df['Number Of Patients In nPCR Summary']])

{3, 4}

### Number Of Patient-Months In nPCR Summary
Data type: float64

Value count: 224

Number of unique values: 73

Percent unique values: 0.000162

Ranges of values: 1 - 

Length of values: 1 - 3

Description: Lists the number of patient-months included in the facility's patients included in the facility's normalized protein catabolic rate (nPCR) summary. The normalized protein catabolic rate (nPCR) is a formula commonly used to assess dietary protein intake in dialysis patients, as a means towards determining nutritional adequacy, a major problem in many ESRD patients. 
The nPCR is reported in grams of urea nitrogen per kilogram per day.
Most guidelines specify maintaining the protein intake above 1.0 – 1.2 g/kg/day in dialysis patients, with values less than 0.8 g/kg/day being equated with malnutrition.

In [152]:
set([(len(str(num))) for num in df['Number Of Patient-Months In nPCR Summary']])

{3, 4, 5}

### nPCR Data Availability Code
Data type: float64

Value count: 7600

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 199, 201, 258, 259

Length of values: 3

Description: Lists whether the facility had sufficient normalized protein catabolic rate (nPCR) data available or the reason for why the data is not available. The normalized protein catabolic rate (nPCR) is a formula commonly used to assess dietary protein intake in dialysis patients, as a means towards determining nutritional adequacy, a major problem in many ESRD patients. 
The nPCR is reported in grams of urea nitrogen per kilogram per day.
Most guidelines specify maintaining the protein intake above 1.0 – 1.2 g/kg/day in dialysis patients, with values less than 0.8 g/kg/day being equated with malnutrition.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure.
- 258 : The dialysis center was not open long enough to supply sufficient measure data. 
- 259 : The dialysis center does not provide hemodialysis and/or peritoneal dialysis to pediatric patients during the reporting period.

In [153]:
df['nPCR Data Availability Code'].value_counts()

259.0    7153
201.0     240
199.0     185
258.0     115
Name: nPCR Data Availability Code, dtype: int64

### Percentage Of Pediatric HD Patients With nPCR
Data type: float64

Value count: 26

Number of unique values: 14

Percent unique values: 0.000031

Ranges of values: 100 -

Length of values: 2 - 3

Description: Lists the percentage of pediatric HD patients with normalized protein catabolic rate (nPCR). The normalized protein catabolic rate (nPCR) is a formula commonly used to assess dietary protein intake in dialysis patients, as a means towards determining nutritional adequacy, a major problem in many ESRD patients. 
The nPCR is reported in grams of urea nitrogen per kilogram per day.
Most guidelines specify maintaining the protein intake above 1.0 – 1.2 g/kg/day in dialysis patients, with values less than 0.8 g/kg/day being equated with malnutrition.

In [154]:
set([(len(str(num))) for num in df['Percentage Of Pediatric HD Patients With nPCR']])

{3, 4, 5}

### SWR Date
Data type: object

Value count: 7626

Number of unique values: 1

Percent unique values: 0.000002

Ranges of values: "01/01/2015 - 12/31/2017"

Length of values: 23

Description: Years Patient Transplant Waitlist Is Based Upon. Standardized Waitlist Ratio (SWR) measure tracks the number of incident patients at the dialysis facility under the age of 75 listed on the kidney or kidney-pancreas transplant waitlist or who received a living donor transplant within the first year of initiating dialysis. SWR is calculated to compare the observed waitlisting rate in the facility to the waitlisting rate that was expected.

In [155]:
df['SWR Date'].value_counts()

01/01/2016 - 12/31/2018    7724
Name: SWR Date, dtype: int64

In [156]:
set([(len(str(num))) for num in df['SWR Date']])

{23}

### SWR Category Text
Data type: object

Value count: 4111

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: As Expected, Worse than Expected, Better than Expected

Length of values: 3, 11, 19, 20

Description: Standardized waitlist ratio (SWR) category text. The standardized waitlist ratio (SWR) measure tracks the number of incident patients at the dialysis facility under the age of 75 listed on the kidney or kidney-pancreas transplant waitlist or who received a living donor transplant within the first year of initiating dialysis. SWR is calculated to compare the observed waitlisting rate in the facility to the waitlisting rate that was expected. 

Value description:
- As Expected          : Patient standardized waitlist ratio (SWR) categorized as “As Expected”       
- Worse than Expected  :  Patient standardized waitlist ratio (SWR) categorized as “Worse than Expected”
- Better than Expected : Patient standardized waitlist ratio (SWR) categorized as “Better than Expected"

In [157]:
df['SWR Category Text'].value_counts()

As Expected             3623
Better than Expected     303
Worse than Expected      238
Name: SWR Category Text, dtype: int64

In [158]:
set([(len(str(num))) for num in df['SWR Category Text']])

{3, 11, 19, 20}

### Patient Transplant Waitlist Data Availability Code
Data type: float64

Value count: 3515

Number of unique values: 4

Percent unique values: 0.000009

Ranges of values: 199, 201, 255, 258

Length of values: 3

Description: Lists whether the facility had sufficient patient transplant waitlist data available or
the reason for why the data is not available.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure. 
- 255 : Medicare determined that the percentage reported was not accurate.
- 258 : The dialysis center was not open long enough to supply sufficient measure data.

In [159]:
df['Patient Transplant Waitlist Data Availability Code'].value_counts()

199.0    3012
258.0     416
201.0     132
Name: Patient Transplant Waitlist Data Availability Code, dtype: int64

### 95% C.I. (Upper Limit) For SWR
Data type: float64

Value count: 4111

Number of unique values: 593

Percent unique values: 0.001318

Ranges of values: 0.23 - 

Length of values: 1 - 5

Description: Lists the upper confident interval limit (95%) for Standardized Waitlist Ratio (SWR) rate per 100 patient-years. The Standardized Waitlist Ratio (SWR) measure tracks the number of incident patients at the dialysis facility under the age of 75 listed on the kidney or kidney-pancreas transplant waitlist or who received a living donor transplant within the first year of initiating dialysis. SWR is calculated to compare the observed waitlisting rate in the facility to the waitlisting rate that was expected. 

In [160]:
set([(len(str(num))) for num in df['95% C.I. (Upper Limit) For SWR']])

{3, 4, 5}

### 95% C.I. (Lower Limit) For SWR
Data type: float64

Value count: 4111

Number of unique values: 214

Percent unique values: 0.511%

Ranges of values: 0.000476 

Length of values: 1 - 4

Description: Lists the lower confident interval limit (95%) for Standardized Waitlist Ratio (SWR) rate per 100 patient-years. The Standardized Waitlist Ratio (SWR) measure tracks the number of incident patients at the dialysis facility under the age of 75 listed on the kidney or kidney-pancreas transplant waitlist or who received a living donor transplant within the first year of initiating dialysis. SWR is calculated to compare the observed waitlisting rate in the facility to the waitlisting rate that was expected. 

In [161]:
set([(len(str(num))) for num in df['95% C.I. (Lower Limit) For SWR']])

{3, 4}

### Number Of Patients In This Facility For SWR
Data type: float64

Value count: 7554

Number of unique values: 145

Percent unique values: 0.000322

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of patients in this facility for Standardized Waitlist Ratio (SWR). The Standardized Waitlist Ratio (SWR) measure tracks the number of incident patients at the dialysis facility under the age of 75 listed on the kidney or kidney-pancreas transplant waitlist or who received a living donor transplant within the first year of initiating dialysis. SWR is calculated to compare the observed waitlisting rate in the facility to the waitlisting rate that was expected. 

In [162]:
set([(len(str(num))) for num in df['Number Of Patients In This Facility For SWR']])

{3, 4, 5}

### Standardized First Kidney Transplant Waitlist Ratio
Data type: float64

Value count: 4111

Number of unique values: 360

Percent unique values: 0.000800

Ranges of values: 0.08 - 

Length of values: 1 - 4

Description: Lists the ratio of standardized waitlist ratio (SWR) in this facility. This measure tracks the number of incident patients at the dialysis facility under the age of 75 listed on the kidney or kidney-pancreas transplant waitlist or who received living donor transplants within the first year of initiating dialysis. 

In [163]:
set([(len(str(num))) for num in df['Standardized First Kidney Transplant Waitlist Ratio']])

{3, 4}

### PPPW Category Text
Data type: object

Value count: 7178

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: As Expected, Worse than Expected, Better than Expected

Length of values: 3, 11, 19, 20

Description: Percentage of prevalent patients waitlisted (PPPW) category text. The PPPW measure tracks the percentage of patients at each dialysis facility who were on the kidney or kidney-pancreas transplant waiting list. Results are averaged across patients prevalent on the last day of each month during the reporting year, adjusted for age.

Value description:
- As Expected          : Patient percentage of prevalent patients waitlisted (PPPW) categorized as “As Expected”       
- Worse than Expected  :  Patient percentage of prevalent patients waitlisted (PPPW) categorized as “Worse than Expected”
- Better than Expected : Patient percentage of prevalent patients waitlisted (PPPW) categorized as “Better than Expected"

In [164]:
df['PPPW Category Text'].value_counts()

As Expected             6659
Better than Expected     478
Worse than Expected      174
Name: PPPW Category Text, dtype: int64

In [165]:
set([(len(str(num))) for num in df['PPPW Category Text']])

{3, 11, 19, 20}

### Patient Prevalent Transplant Waitlist Data Availability Code
Data type: float64

Value count: 448

Number of unique values: 3

Percent unique values: 0.000007

Ranges of values: 199, 201, 258

Length of values: 3

Description: Lists whether the facility had sufficient patient prevalent transplant waitlist data available or the reason for why the data is not available.

Value description:
- 199 : Not enough patients to report on this measure. Call the dialysis center to discuss this measure.
- 201 : Data not reported. Call the dialysis center to discuss this quality measure. 
- 258 : The dialysis center was not open long enough to supply sufficient measure data.

In [166]:
df['Patient Prevalent Transplant Waitlist Data Availability Code'].value_counts()

258.0    262
199.0    132
201.0     18
255.0      1
Name: Patient Prevalent Transplant Waitlist Data Availability Code, dtype: int64

### 95% C.I. (Upper Limit) For PPPW
Data type: float64

Value count: 7178

Number of unique values: 766

Percent unique values: 0.001702

Ranges of values: 0 - 

Length of values: 1 - 4

Description: Lists the upper confident interval limit (95%) for Percentage of Prevalent Patients Waitlisted (PPPW) rate per 100 patient-years. The PPPW measure tracks the percentage of patients at each dialysis facility who were on the kidney or kidney-pancreas transplant waiting list. Results are averaged across patients prevalent on the last day of each month during the reporting year, adjusted for age.

In [167]:
set([(len(str(num))) for num in df['95% C.I. (Upper Limit) For PPPW']])

{3, 4}

### 95% C.I. (Lower Limit) For PPPW
Data type: float64

Value count: 7178

Number of unique values: 355

Percent unique values: 0.000789

Ranges of values: 0.1 - 

Length of values: 1 - 4

Description: Lists the lower confident interval limit (95%) for Percentage of Prevalent Patients Waitlisted (PPPW) rate per 100 patient-years. The PPPW measure tracks the percentage of patients at each dialysis facility who were on the kidney or kidney-pancreas transplant waiting list. Results are averaged across patients prevalent on the last day of each month during the reporting year, adjusted for age.

In [168]:
set([(len(str(num))) for num in df['95% C.I. (Lower Limit) For PPPW']])

{3, 4}

### Number Of Patients For PPPW
Data type: float64

Value count: 7555

Number of unique values: 269

Percent unique values: 0.000598

Ranges of values: 0 - 

Length of values: 1 - 3

Description: Lists the number of patients included in the facility's percentage of prevalent patients waitlisted (PPPW). The PPPW measure tracks the percentage of patients at each dialysis facility who were on the kidney or kidney-pancreas transplant waiting list. Results are averaged across patients prevalent on the last day of each month during the reporting year, adjusted for age.

In [169]:
set([(len(str(num))) for num in df['Number Of Patients For PPPW']])

{3, 4, 5}

### Percentage Of Prevalent Patients Waitlisted
Data type: float64

Value count: 7178

Number of unique values: 571

Percent unique values: 0.001269

Ranges of values: 0.1 - 

Length of values: 1 - 4

Description: Lists the percentage of prevalent patients waitlisted.

In [170]:
set([(len(str(num))) for num in df['Percentage Of Prevalent Patients Waitlisted']])

{3, 4}

### Location
Data type: object 

Value count: 7162

Number of unique values: 7043 

Percent unique values: 0.015653

Ranges of values: 

Length of values: 3, 23, 25 - 29

Description: Lists the coorinate location that corresponds to the facility listed.

In [171]:
set([(len(str(num))) for num in df['Location']])

{3, 23, 24, 25, 26, 27, 28, 29}

# Data Cleaning

## Fill NA

In [172]:
df['Chain Organization'] = df['Chain Organization'].fillna('INDEPENDENT')

In [173]:
fillwithmedian = ['Star Rating', 
                'Percentage Of Medicare Patients With Hgb < 10 g/dL', 
                'Percentage Of Medicare Patients With Hgb > 12 g/dL', 
                'Number Of Dialysis Patients With Hgb Data', 
                'Number Of Patients Included In The Transfusion Summary', 
                'Percent Of Adult HD Patients With Kt/V >= 1.2', 
                'Number Of Adult HD Patients With Kt/V Data', 
                'Number Of Adult HD Patient-Months With Kt/V Data', 
                'Number Of Adult PD Patients With Kt/V Data',  
                'Number Of Pediatric HD Patients With Kt/V Data', 
                'Number Of Patients In Hypercalcemia Summary', 
                'Number Of Patient-Months In Hypercalcemia Summary', 
                'Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 mg/dL)', 
                'Number Of Patients In Serum Phosphorus Summary', 
                'Number Of Patient-Months In Serum Phosphorus Summary', 
                'Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 mg/dL', 
                'Percentage Of Adult Patients With Serum Phosphorus Between 3.5 - 4.5 mg/dL', 
                'Percentage Of Adult Patients With Serum Phosphorus Between 4.6 - 5.5 mg/dL', 
                'Percentage Of Adult Patients With Serum Phosphorus Between 5.6 - 7.0 mg/dL', 
                'Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 mg/dL', 
                'Number Of Patients Included In Hospitalization Summary', 
                'Number Of Hospitalizations Included In Hospital Readmission Summary', 
                'Number Of Patients Included In Survival Summary', 
                'Mortality Rate (Facility)', 
                'Mortality Rate: Upper Confidence Limit (97.5%)', 
                'Mortality Rate: Lower Confidence Limit (2.5%)', 
                'Readmission Rate (Facility)', 
                'Readmission Rate: Upper Confidence Limit (97.5%)', 
                'Readmission Rate: Lower Confidence Limit (2.5%)', 
                'Hospitalization Rate (Facility)', 
                'Hospitalization Rate: Upper Confidence Limit (97.5%)', 
                'Hospitalization Rate: Lower Confidence Limit (2.5%)', 
                'Number Of Pediatric PD Patients With Kt/V Data', 
                'Standard Infection Ratio', 
                'SIR: Upper Confidence Limit (97.5%)', 
                'SIR: Lower Confidence Limit (2.5%)', 
                'Transfusion Rate (Facility)', 
                'Transfusion Rate: Upper Confidence Limit (97.5%)', 
                'Transfusion Rate: Lower Confidence Limit (2.5%)', 
                'Number Of Patients Included In Fistula Summary', 
                'Fistula Rate (Facility)', 
                'Fistula Rate: Upper Confidence Limit (97.5%)', 
                'Fistula Rate: Lower Confidence Limit (2.5%)', 
                'Number Of Patients In Long Term Catheter Summary', 
                'Number Of Patient-Months In Long Term Catheter Summary', 
                'Percentage Of Adult Patients With Long Term Catheter In Use', 
                'Number Of Patients In nPCR Summary', 
                '95% C.I. (Upper Limit) For SWR', 
                '95% C.I. (Lower Limit) For SWR', 
                'Number Of Patients In This Facility For SWR', 
                'Standardized First Kidney Transplant Waitlist Ratio', 
                '95% C.I. (Upper Limit) For PPPW', 
                '95% C.I. (Lower Limit) For PPPW', 
                'Number Of Patients For PPPW', 
                'Percentage Of Prevalent Patients Waitlisted']

In [174]:
df[fillwithmedian] = df[fillwithmedian].fillna(df[fillwithmedian].median())

In [175]:
dropcolumns = ['Star Rating Data Availability Code', 
               'Address Line 2', 
               'Hgb < 10 Data Availability Code', 
               'Hgb > 12 Data Availability Code', 
               'Patient Transfusion Data Availability Code', 
               'Adult HD Kt/V Data Availability Code',
               'Percentage Of Adult PD PTS With Kt/V >= 1.7', 
               'Percentage Of Pediatric HD Patients With Kt/V >= 1.2', 
               'Number Of Adult PD Patient-Months With Kt/V Data', 
               'Number Of Pediatric HD Patient-Months With Kt/V Data', 
               'Hypercalcemia Data Availability Code', 
               'Serum Phosphorus Data Availability Code', 
               'Patient Hospitalization Data Availability Code', 
               'Patient Hospital Readmission Data Availability Code', 
               'Patient Survival Data Availability Code', 
               'Number Of Pediatric PD Patient-Months With Kt/V Data', 
               'Percentage Of Pediatric PD Patients With Kt/V >= 1.8', 
               'Patient Infection Data Availability Code', 
               'Fistula Data Availability Code', 
               'Long Term Catheter Data Availability Code', 
               'Number Of Patient-Months In nPCR Summary', 
               'Percentage Of Pediatric HD Patients With nPCR', 
               'Patient Transplant Waitlist Data Availability Code', 
               'Patient Prevalent Transplant Waitlist Data Availability Code', 
               'Location']
               

In [176]:
df.drop(df[dropcolumns], axis=1, inplace=True)

In [177]:
backfill = ['Patient Transfusion Category Text', 
                'Adult PD Kt/V Data Availability Code', 
                'Pediatric HD Kt/V Data Availability Code', 
                'Patient Hospitalization Category Text', 
                'Patient Hospital Readmission Category Text', 
                'Patient Survival Category Text', 
                'Pediatric PD Kt/V Data Availability Code', 
                'Patient Infection Category Text', 
                'Fistula Category Text', 
                'nPCR Data Availability Code', 
                'SWR Category Text', 
                'PPPW Category Text']


In [178]:
df[backfill] = df[backfill].fillna(method='bfill')

In [179]:
df.isnull().values.any()

True

## Change dtypes

In [180]:
isdateframe = ['Star Rating Date', 'Claims Date', 'CROWNWeb Date', 'STrR Date', 'SHR Date', 'SRR Date', 'SMR Date', 'SIR Date', 'SWR Date']

In [181]:
isdate = ['Certification Or Recertification Date']

In [182]:
df[isdate] = df[isdate].astype('datetime64[ns]')

In [183]:
df.iloc[:, :60].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7724 entries, 0 to 7723
Data columns (total 60 columns):
 #   Column                                                                                   Non-Null Count  Dtype         
---  ------                                                                                   --------------  -----         
 0   Provider Number                                                                          7724 non-null   int64         
 1   Network                                                                                  7724 non-null   int64         
 2   Facility Name                                                                            7724 non-null   object        
 3   Star Rating Date                                                                         7724 non-null   object        
 4   Star Rating                                                                              7724 non-null   float64       
 5   Address Line 

In [184]:
df.iloc[:, 60:].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7724 entries, 0 to 7723
Data columns (total 34 columns):
 #   Column                                                       Non-Null Count  Dtype  
---  ------                                                       --------------  -----  
 0   Hospitalization Rate (Facility)                              7724 non-null   float64
 1   Hospitalization Rate: Upper Confidence Limit (97.5%)         7724 non-null   float64
 2   Hospitalization Rate: Lower Confidence Limit (2.5%)          7724 non-null   float64
 3   Number Of Pediatric PD Patients With Kt/V Data               7724 non-null   float64
 4   Pediatric PD Kt/V Data Availability Code                     7724 non-null   float64
 5   SIR Date                                                     7724 non-null   object 
 6   Patient Infection Category Text                              7724 non-null   object 
 7   Standard Infection Ratio                                     7724 non-null   f

## Fix value format

In [185]:
df['Zip'] = df['Zip'].astype(str).str.zfill(5)

In [186]:
set([(len(str(num))) for num in df['Zip']])

{5}

In [187]:
df['Star Rating'] = df['Star Rating'].astype('int64')

In [188]:
df['Chain Owned'].unique()

array(['Yes', 'No'], dtype=object)

In [189]:
df['Chain Owned'] = df['Chain Owned'].replace(to_replace=['No', 'Yes'], value=[0, 1])

In [190]:
df['Profit Or Non-Profit'] = df['Profit Or Non-Profit'].replace(to_replace=['Non-Profit', 'Profit'], value=[0, 1])

In [191]:
df.iloc[:5, :60].head().T

0  \
Provider Number                                                       32647   
Network                                                                  15   
Facility Name                                            FMC NORTH MOUNTAIN   
Star Rating Date                                    01/01/2016 - 12/31/2019   
Star Rating                                                               4   
Address Line 1                                      16605 NORTH 28TH AVENUE   
City                                                                PHOENIX   
State                                                                    AZ   
Zip                                                                   85053   
County                                                             MARICOPA   
Phone Number                                                 (602) 863-7954   
Profit Or Non-Profit                                                      1   
Chain Owned                                                               1   
Chain Organization                                   FRESENIUS MEDICAL CARE   
Late Shift                                                                0   
Number Of Dialysis Stations                                              25   
Offers In-Center Hemodialysis                                             1   
Offers Peritoneal Dialysis                                                0   
Offers Home Hemodialysis Training                                         0   
Certification Or Recertification Date                   2016-10-12 00:00:00   
Claims Date                                         01/01/2019 - 12/31/2019   
CROWNWeb Date                                       01/01/2019 - 12/31/2019   
STrR Date                                           01/01/2019 - 12/31/2019   
Percentage Of Medicare Patients With Hgb < 10 g/dL                        8   
Percentage Of Medicare Patients With Hgb > 12 g/dL                        0   
Number Of Dialysis Patients With Hgb Data                                25   
Patient Transfusion Category Text                               As Expected   
Number Of Patients Included In The Transfusion ...                       56   
Percent Of Adult HD Patients With Kt/V >= 1.2                            98   
Adult PD Kt/V Data Availability Code                                    257   
Pediatric HD Kt/V Data Availability Code                                259   
Number Of Adult HD Patients With Kt/V Data                               91   
Number Of Adult HD Patient-Months With Kt/V Data                        608   
Number Of Adult PD Patients With Kt/V Data                                0   
Number Of Pediatric HD Patients With Kt/V Data                            0   
Number Of Patients In Hypercalcemia Summary                              96   
Number Of Patient-Months In Hypercalcemia Summary                       665   
Percentage Of Adult Patients With Hypercalcemia...                        2   
Number Of Patients In Serum Phosphorus Summary                          108   
Number Of Patient-Months In Serum Phosphorus Su...                      720   
Percentage Of Adult Patients With Serum Phospho...                        7   
Percentage Of Adult Patients With Serum Phospho...                       28   
Percentage Of Adult Patients With Serum Phospho...                       30   
Percentage Of Adult Patients With Serum Phospho...                       26   
Percentage Of Adult Patients With Serum Phospho...                        9   
SHR Date                                            01/01/2019 - 12/31/2019   
SRR Date                                            01/01/2019 - 12/31/2019   
SMR Date                                            01/01/2016 - 12/31/2019   
Patient Hospitalization Category Text                           As Expected   
Patient Hospital Readmission Category Text                      As Expected   
Patient Survival Category Text               

In [192]:
df.iloc[:5, 60:].head().T

0  \
Hospitalization Rate (Facility)                                       224.5   
Hospitalization Rate: Upper Confidence Limit (9...                    359.9   
Hospitalization Rate: Lower Confidence Limit (2...                    146.1   
Number Of Pediatric PD Patients With Kt/V Data                            0   
Pediatric PD Kt/V Data Availability Code                                259   
SIR Date                                            01/01/2019 - 12/31/2019   
Patient Infection Category Text                                 As Expected   
Standard Infection Ratio                                               0.38   
SIR: Upper Confidence Limit (97.5%)                                    1.24   
SIR: Lower Confidence Limit (2.5%)                                     0.06   
Transfusion Rate (Facility)                                            24.3   
Transfusion Rate: Upper Confidence Limit (97.5%)                      107.9   
Transfusion Rate: Lower Confidence Limit (2.5%)                           7   
Fistula Category Text                                           As Expected   
Number Of Patients Included In Fistula Summary                          109   
Fistula Rate (Facility)                                                72.5   
Fistula Rate: Upper Confidence Limit (97.5%)                           87.3   
Fistula Rate: Lower Confidence Limit (2.5%)                            56.6   
Number Of Patients In Long Term Catheter Summary                        109   
Number Of Patient-Months In Long Term Catheter ...                      726   
Percentage Of Adult Patients With Long Term Cat...                       11   
Number Of Patients In nPCR Summary                                        0   
nPCR Data Availability Code                                             259   
SWR Date                                            01/01/2016 - 12/31/2018   
SWR Category Text                                               As Expected   
95% C.I. (Upper Limit) For SWR                                         2.37   
95% C.I. (Lower Limit) For SWR                                         0.18   
Number Of Patients In This Facility For SWR                              18   
Standardized First Kidney Transplant Waitlist R...                     0.82   
PPPW Category Text                                              As Expected   
95% C.I. (Upper Limit) For PPPW                                          44   
95% C.I. (Lower Limit) For PPPW                                         8.8   
Number Of Patients For PPPW                                              93   
Percentage Of Prevalent Patients Waitlisted                            21.6   

                                                                          1  \
Hospitalization Rate (Facility)                                       118.4   
Hospitalization Rate: Upper Confidence Limit (9...                    236.3   
Hospitalization Rate: Lower Confidence Limit (2...                     63.2   
Number Of Pediatric PD Patients With Kt/V Data                            0   
Pediatric PD Kt/V Data Availability Code                                259   
SIR Date                                            01/01/2019 - 12/31/2019   
Patient Infection Category Text                                 As Expected   
Standard Infection Ratio                                               0.87   
SIR: Upper Confidence Limit (97.5%)                                    2.36   
SIR: Lower Confidence Limit (2.5%)                                     0.22   
Transfusion Rate (Facility)                                            13.9   
Transfusion Rate: Upper Confidence Limit (97.5%)                      114.1   
Transfusion Rate: Lower Confidence Limit (2.5%)                         2.4   
Fistula Category Text                                           As Expected   
Number Of Patients Included In Fistula Summary                           53   
Fistula Rate (Facility)                     

# Export to new csv

In [193]:
import os

In [194]:
os.getcwd()

'/Users/nicholehartz/Documents/DataScience/Projects/Capstone2'

In [195]:
df.to_csv('Data/capstone2_dialysis_cleaned_data.csv')